'use strict'

/**
 * ═══════════════════════════════════════════════════════════════════════════
 *  LES TEXTES DU SERVEUR, EN TROIS LANGUES
 * ══════════════════════════════════════════════════════════════════════════
 *  Ce fichier ne contient QUE des phrases. Aucune logique, aucun require : il
 *  se lit comme une liste, et c’est ce qui permet de le relire pour de vrai.
 *
 *  ⚠️ LES TROIS TABLES ONT LES MEMES CLES. Le banc d’essai le vérifie, et
 *     vérifie aussi que les marqueurs `{v1}`, `{v2}`… sont les mêmes partout :
 *     un marqueur oublié dans une traduction, et c’est une valeur qui disparaît
 *     de la phrase sans que personne ne s’en aperçoive.
 *
 *  ⚠️ L’ORDRE DES MOTS N’EST PAS LE MÊME D’UNE LANGUE À L’AUTRE. C’est pour
 *     ça que les valeurs sont insérées par marqueur et jamais concaténées : une
 *     phrase coupée en morceaux recollés n’est pas traduisible.
 *
 *  ⚠️ ON NE MET PAS ICI CE QUE LES JOUEURS ÉCRIVENT. Un message de chat, un
 *     pseudo, une raison de bannissement tapée à la main : ça traverse tel quel.
 * ══════════════════════════════════════════════════════════════════════════
 */

module.exports = {
  fr: {
    'server.ecoute-jeu': 'jeu : UDP {v1}:{v2}',
    'server.ecoute-monde': 'monde et navigateur : TCP {v1}:{v2}',
    'server.transport': 'transport : {v1}',
    'cmd.cap.n': 'nord',
    'cmd.cap.ne': 'nord-est',
    'cmd.cap.e': 'est',
    'cmd.cap.se': 'sud-est',
    'cmd.cap.s': 'sud',
    'cmd.cap.so': 'sud-ouest',
    'cmd.cap.o': 'ouest',
    'cmd.cap.no': 'nord-ouest',
    'session.expulse-remplace': 'remplacé par une autre connexion',
    'session.reprise-ailleurs': 'identité reprise ailleurs',
    'session.te-voila-hote': 'Tu es maintenant l’hôte de la partie.',
    'cmd.equipier-pret': '{v1} est prêt ({v2}).',
    'cmd.equipier-plus-pret': '{v1} n’est plus prêt ({v2}).',
    'cmd.coffre-depot': '{v1} a déposé {v2} {v3}',
    'cmd.coffre-retrait': '{v1} a pris {v2} {v3}',
    'cmd.dont-refusees': ', {v1} refusée(s)',
    'ressources.dont-refusees': ', {v1} refusée(s)',
    'session.remplace': '{v1} remplacé par une nouvelle connexion de la même identité.',
    'cmd.figee': 'figée',
    'cmd.tick': 'tick {v1} ms (pire {v2})',
    'cmd.tick-na': 'tick N/A',
    'cmd.processeur': 'processeur {v1}',
    'annuaire.annuaire-eteint-annuaire-1-et': 'annuaire : éteint (ANNUAIRE=1 et ANNUAIRE_URL pour l’allumer).',
    'annuaire.annuaire-injoignable-depuis-essais-on': 'annuaire injoignable depuis {v1} essais ({v2}) — on réessaiera.',
    'annuaire.annuaire-de-nouveau-joignable': 'annuaire : de nouveau joignable.',
    'annuaire.annuaire-url-invalide': 'ANNUAIRE_URL invalide',
    'annuaire.http': 'HTTP {v1}',
    'annuaire.delai-depasse': 'délai dépassé',
    'cmd.texte': '/{v1} — {v2}',
    'cmd.commandes-aide-commande-pour-le': 'Commandes ({v1}) : {v2} · /aide <commande> pour le détail',
    'cmd.ton-identite-ton-role-ton': 'ton identité, ton rôle, ton temps de jeu',
    'cmd.role': '{v1} — rôle {v2}',
    'cmd.identite': 'identité {v1}',
    'cmd.anonyme-pas-d-identite-signee': 'anonyme (pas d’identité signée)',
    'cmd.equipe': 'équipe {v1}',
    'cmd.serveur-v-protocole-min-transport': '{v1} — serveur v{v2}, protocole {v3} (min {v4}), transport {v5}',
    'cmd.qui-est-connecte': 'qui est connecté',
    'cmd.hote': 'hôte',
    'cmd.ms': '{v1}{v2} — {v3} ms',
    'cmd.tu-es-a': 'Tu es à {v1}, {v2}, {v3}.',
    'cmd.qui-est-autour-de-toi': 'qui est autour de toi [mètres]',
    'cmd.personne-a-moins-de-m': 'Personne à moins de {v1} m.',
    'cmd.a-m': '{v1} à {v2} m',
    'cmd.tu-es-seul-en-jeu': 'Tu es seul en jeu.',
    'cmd.m': '{v1} — {v2} m, {v3}',
    'cmd.le-serveur-ne-retient-rien': 'Le serveur ne retient rien pour l’instant.',
    'cmd.a-pose-le-point-de': '{v1} a posé le point de rendez-vous.',
    'cmd.point-de-rendez-vous-oublie': 'Point de rendez-vous oublié.',
    'cmd.aucun-point-de-rendez-vous': 'Aucun point de rendez-vous. Tape /rdv poser là où tu veux que les autres arrivent.',
    'cmd.rendez-vous-pose-par-a': 'Rendez-vous posé par {v1} — à {v2} m de toi, {v3}. En jeu, F5 t’y emmène.',
    'cmd.poser-un-repere-ici-nom': 'poser un repère ici [nom]',
    'cmd.impossible-trop-de-reperes-sur': 'Impossible : trop de repères sur ce serveur.',
    'cmd.a-pose-le-repere-n': '{v1} a posé le repère « {v2} » (n°{v3}).',
    'cmd.la-liste-des-reperes': 'la liste des repères',
    'cmd.aucun-repere-pour-l-instant': 'Aucun repère pour l’instant. /marquer en pose un.',
    'cmd.n-m': 'n°{v1} {v2} — {v3} m, {v4}',
    'cmd.les-gestes-ne-sont-pas': 'Les gestes ne sont pas disponibles sur ce serveur.',
    'cmd.au-choix': 'Au choix : {v1}.',
    'cmd.doucement-trop-de-gestes-d': 'Doucement : trop de gestes d’un coup.',
    'cmd.message-prive-nom-texte': 'message privé <nom> <texte>',
    'cmd.donne-un-nom-et-un': 'Donne un nom et un message : /mp Alex on se retrouve au phare',
    'cmd.personne-de-ce-nom-ou': 'Personne de ce nom, ou plusieurs correspondent.',
    'cmd.tu-te-parles-deja-tout': 'Tu te parles déjà tout seul.',
    'cmd.prive-a': '(privé à {v1}) {v2}',
    'cmd.equipes-equipe-equipe-creer-nom': 'équipes : /equipe, /equipe creer <nom>, /equipe rejoindre <nom>, /equipe quitter',
    'cmd.les-equipes-ne-sont-pas': 'Les équipes ne sont pas disponibles sur ce serveur.',
    'cmd.aucune-equipe-equipe-creer-nom': 'Aucune équipe. /equipe creer <nom> en fait une.',
    'cmd.pret-s': '{v1} ({v2}) : {v3} — {v4}/{v5} prêt(s)',
    'cmd.donne-un-nom-equipe-creer': 'Donne un nom : /equipe creer Phare',
    'cmd.impossible-trop-d-equipes-ou': 'Impossible : trop d’équipes, ou nom vide.',
    'cmd.cree-l-equipe': '{v1} crée l’équipe « {v2} ».',
    'cmd.aucune-equipe-de-ce-nom': 'Aucune équipe de ce nom. /equipe pour la liste.',
    'cmd.rejoint': '{v1} rejoint « {v2} ».',
    'cmd.tu-n-es-dans-aucune': 'Tu n’es dans aucune équipe.',
    'cmd.tu-quittes': 'Tu quittes « {v1} ».',
    'cmd.au-choix-equipe-creer-rejoindre': 'Au choix : /equipe · creer · rejoindre · quitter',
    'cmd.se-declarer-pret-ou-plus': 'se déclarer prêt, ou plus prêt',
    'cmd.rejoins-une-equipe-d-abord': 'Rejoins une équipe d’abord : /equipe creer <nom>',
    'cmd.toute-l-equipe-est-prete': 'Toute l’équipe « {v1} » est prête.',
    'cmd.objectifs-activite-activite-creer-titre': 'objectifs : /activite, /activite creer <titre> | <étape> | <étape>, /activite demarrer <n°>, /activite fait <n°> <étape>',
    'cmd.les-activites-ne-sont-pas': 'Les activités ne sont pas disponibles sur ce serveur.',
    'cmd.aucune-activite-activite-creer-reparer': 'Aucune activité. /activite creer Réparer le générateur | Trouver la pièce | La poser',
    'cmd.donne-un-titre-activite-creer': 'Donne un titre : /activite creer Réparer le générateur | Trouver la pièce',
    'cmd.impossible-trop-d-activites-en': 'Impossible : trop d’activités en cours.',
    'cmd.propose-n-etape-s-activite': '{v1} propose « {v2} » (n°{v3}, {v4} étape(s)). /activite demarrer {v5}',
    'cmd.aucune-activite-proposee-sous-ce': 'Aucune activité proposée sous ce numéro.',
    'cmd.commence': '« {v1} » commence.',
    'cmd.rien-a-cocher-verifie-le': 'Rien à cocher : vérifie le numéro d’activité et celui de l’étape.',
    'cmd.est-terminee-bravo': '« {v1} » est terminée. Bravo.',
    'cmd.a-fait': '{v1} a fait « {v2} » ({v3}).',
    'cmd.aucune-activite-sous-ce-numero': 'Aucune activité sous ce numéro.',
    'cmd.est-abandonnee': '« {v1} » est abandonnée.',
    'cmd.au-choix-activite-creer-demarrer': 'Au choix : /activite · creer · demarrer · fait · finir',
    'cmd.le-coffre-commun-n-est': 'Le coffre commun n’est pas disponible sur ce serveur.',
    'cmd.aucun-mouvement-pour-l-instant': 'Aucun mouvement pour l’instant.',
    'cmd.le-coffre-commun-est-vide': 'Le coffre commun est vide. En jeu, F10 y dépose ce que tu portes.',
    'cmd.ce-que-quelqu-un-porte': 'ce que quelqu’un porte <nom>',
    'cmd.l-inventaire-n-est-pas': 'L’inventaire n’est pas disponible sur ce serveur.',
    'cmd.n-a-rien-declare-son': '{v1} n’a rien déclaré (son mod ne lit pas encore l’inventaire).',
    'cmd.retirer-un-repere-n': 'retirer un repère <n°>',
    'cmd.donne-le-numero-du-repere': 'Donne le numéro du repère : /effacer 3',
    'cmd.repere-n-retire': 'Repère n°{v1} retiré.',
    'cmd.aucun-repere-n': 'Aucun repère n°{v1}.',
    'cmd.changer-la-meteo-nom': 'changer la météo <nom>',
    'cmd.donne-une-meteo-meteo-orage': 'Donne une météo : /meteo orage',
    'cmd.la-meteo-passe-a': 'La météo passe à « {v1} ».',
    'cmd.changer-l-heure-h-min': 'changer l’heure <h> [min]',
    'cmd.donne-une-heure-entre-0': 'Donne une heure entre 0 et 23 : /heure 21',
    'cmd.il-est-maintenant-h': 'Il est maintenant {v1} h {v2}.',
    'cmd.la-cadence-du-cycle-jour': 'la cadence du cycle jour/nuit [minutes de jeu par minute réelle]',
    'cmd.l-horloge-du-serveur-n': 'L’horloge du serveur n’est pas disponible.',
    'cmd.jour-h-cadence-meteo': 'Jour {v1}, {v2} h {v3} — cadence {v4}, météo {v5}.',
    'cmd.donne-un-nombre-entre-0': 'Donne un nombre entre 0 (figée) et 240.',
    'cmd.l-horloge-est-figee': 'L’horloge est figée.',
    'cmd.le-temps-avance-de-min': 'Le temps avance de {v1} min de jeu par minute réelle.',
    'cmd.le-mot-du-jour-vide': 'le mot du jour (vide pour l’effacer)',
    'cmd.impossible-d-enregistrer-le-mot': 'Impossible d’enregistrer le mot du jour.',
    'cmd.mot-du-jour-efface': 'Mot du jour effacé.',
    'cmd.mot-du-jour': 'Mot du jour : {v1}',
    'cmd.expulser-quelqu-un-nom-raison': 'expulser quelqu’un <nom> [raison]',
    'cmd.donne-un-nom-expulser-alex': 'Donne un nom : /expulser Alex',
    'cmd.tu-ne-peux-pas-t': 'Tu ne peux pas t’expulser toi-même.',
    'cmd.tu-ne-peux-pas-agir': 'Tu ne peux pas agir sur quelqu’un d’un rang égal ou supérieur.',
    'cmd.expulse-par-un-responsable': 'expulsé par un responsable',
    'cmd.expulse': 'expulsé',
    'cmd.a-ete-expulse-il-peut': '{v1} a été expulsé. Il peut revenir tout de suite — /bannir {v2} 1h pour que ça tienne.',
    'cmd.bannir-nom-duree-30m-2h': 'bannir <nom> [durée: 30m 2h 7j, vide = définitif] [raison]',
    'cmd.la-moderation-n-est-pas': 'La modération n’est pas disponible sur ce serveur.',
    'cmd.donne-un-nom-bannir-alex': 'Donne un nom : /bannir Alex 2h insultes',
    'cmd.personne-de-ce-nom-en': 'Personne de ce nom en jeu. Pour bannir un absent, donne son empreinte à /bannir-id.',
    'cmd.tu-ne-peux-pas-te': 'Tu ne peux pas te bannir toi-même.',
    'cmd.duree-illisible-exemples-30m-2h': 'Durée illisible. Exemples : 30m, 2h, 7j, ou rien pour définitif.',
    'cmd.impossible-ni-identite-ni-adresse': 'Impossible : ni identité ni adresse à viser.',
    'cmd.attention-une-adresse-change-et': ' — attention : une adresse change et peut être partagée par plusieurs personnes',
    'cmd.banni-sur-son': '{v1} banni {v2} sur son {v3}{v4}.',
    'cmd.donne-une-empreinte-une-adresse': 'Donne une empreinte, une adresse ou un nom : /debannir a1b2c3…',
    'cmd.bannissement-s-leve-s': '{v1} bannissement(s) levé(s).',
    'cmd.rien-ne-correspond': 'Rien ne correspond.',
    'cmd.empecher-quelqu-un-de-parler': 'empêcher quelqu’un de parler <nom> [durée]',
    'cmd.donne-un-nom-museler-alex': 'Donne un nom : /museler Alex 15m',
    'cmd.duree-illisible-exemples-15m-2h': 'Durée illisible. Exemples : 15m, 2h.',
    'cmd.tu-ne-peux-plus-parler': 'Tu ne peux plus parler ({v1}).',
    'cmd.ne-peut-plus-parler-2': '{v1} ne peut plus parler — {v2}.',
    'cmd.donne-un-nom-ou-une': 'Donne un nom ou une empreinte.',
    'cmd.silence-s-leve-s': '{v1} silence(s) levé(s).',
    'cmd.aucune-sanction-en-vigueur': 'Aucune sanction en vigueur.',
    'cmd.texte-3': '{v1} {v2} ({v3}) — {v4}{v5}',
    'cmd.donner-un-role-nom-empreinte': 'donner un rôle <nom|empreinte> <proprietaire|admin|moderateur|joueur|aucun>',
    'cmd.les-roles-ne-sont-pas': 'Les rôles ne sont pas disponibles sur ce serveur.',
    'cmd.exemple-role-alex-moderateur': 'Exemple : /role Alex moderateur',
    'cmd.ce-joueur-n-a-pas': 'Ce joueur n’a pas d’identité signée : impossible de lui donner un rôle durable.',
    'cmd.tu-es-maintenant': 'Tu es maintenant {v1}.',
    'cmd.ton-role-a-ete-retire': 'Ton rôle a été retiré.',
    'cmd.est-maintenant': '{v1} est maintenant {v2}.',
    'cmd.role-retire': 'Rôle retiré.',
    'cmd.le-profil-de-quelqu-un': 'le profil de quelqu’un <nom>',
    'cmd.les-profils-ne-sont-pas': 'Les profils ne sont pas disponibles sur ce serveur.',
    'cmd.joue-en-anonyme-aucun-profil': '{v1} joue en anonyme : aucun profil durable.',
    'cmd.profil-introuvable': 'Profil introuvable.',
    'cmd.session-s-h-role': '{v1} [{v2}] — {v3} session(s), {v4} h, rôle {v5}{v6}',
    'cmd.toutes-les-places-de-joueur': 'Toutes les places de joueur sont prises.',
    'cmd.revient-en-jeu': '{v1} revient en jeu.',
    'cmd.tu-es-l-hote-passe': 'Tu es l’hôte : passe la main avant (quitte et reviens, ou attends qu’un autre joue).',
    'cmd.passe-spectateur': '{v1} passe spectateur.',
    'cmd.l-etat-du-serveur-reseau': 'l’état du serveur : réseau, ticks, mémoire',
    'cmd.les-mesures-ne-sont-pas': 'Les mesures ne sont pas disponibles sur ce serveur.',
    'cmd.memoire-mo': 'mémoire {v1} Mo',
    'cmd.reseau-ko-s': 'réseau {v1} ↓ / {v2} ↑ ko/s',
    'cmd.reseau-n-a': 'réseau N/A',
    'cmd.instantane': 'instantané {v1}',
    'cmd.entites': 'entités {v1}',
    'cmd.creatures': 'créatures {v1}',
    'cmd.ce-que-le-mod-a': 'ce que le mod a réussi à faire dans le jeu <nom>',
    'cmd.n-a-encore-rien-signale': '{v1} n’a encore rien signalé.',
    'cmd.les-creatures-que-l-hote': 'les créatures que l’hôte voit',
    'cmd.le-suivi-des-creatures-n': 'Le suivi des créatures n’est pas disponible.',
    'cmd.aucune-creature-signalee-c-est': 'Aucune créature signalée. C’est l’hôte qui les rapporte.',
    'cmd.le-systeme-de-ressources-n': 'Le système de ressources n’est pas disponible.',
    'cmd.ressource-s-rechargee-s': '{v1} ressource(s) rechargée(s){v2}.',
    'cmd.aucune-ressource-installee': 'Aucune ressource installée.',
    'cmd.retenu': 'Retenu : {v1}. {v2}',
    'cmd.tu-n-as-pas-le': 'Tu n’as pas le droit de faire ça.',
    'cmd.la-commande-a-echoue': 'La commande a échoué : {v1}',
    'cmd.commande-inconnue-tape-aide': 'Commande inconnue : /{v1}. Tape /aide.',
    'cmd.l-hote': 'l’hôte',
    'cmd.un-moderateur': 'un modérateur',
    'cmd.le-proprietaire': 'le propriétaire',
    'cmd.cette-commande-est-reservee-a': 'Cette commande est réservée à {v1} (tu es {v2}).',
    'cmd.aide.aide': 'la liste des commandes',
    'cmd.aide.serveur': 'la version du serveur et son transport',
    'cmd.aide.ou': 'ta position',
    'cmd.aide.radar': 'la direction et la distance de chacun (radar en texte)',
    'cmd.aide.rdv': 'le point de rendez-vous (/rdv poser pour le fixer ici)',
    'cmd.aide.coffre': 'le coffre commun : /coffre, /coffre journal',
    'cmd.aide.debannir': 'lever un bannissement <empreinte|adresse|nom>',
    'cmd.aide.demuseler': 'rendre la parole <empreinte|adresse|nom>',
    'cmd.aide.sanctions': 'la liste des bannissements et des silences',
    'cmd.aide.spectateur': 'passer spectateur, ou revenir en jeu',
    'cmd.aide.ressources': 'les ressources du serveur : /ressources, /ressources recharger',
    'cmd.aide.transport': 'par quel chemin passent les paquets, et pourquoi pas les autres',
    'cmd.un-administrateur': 'un administrateur',
    'cmd.aide.geste': 'faire un geste ({v1})',
    'cmd.sessions-heures': '{v1} session(s), {v2} h de jeu',
    'cmd.banni-raison': 'banni : {v1}',
    'cmd.sans-raison-donnee': 'sans raison donnée',
    'cmd.museler-session': '{v1} ne peut plus parler — {v2}. Sans identité signée et derrière une adresse partagée, ça ne tient que le temps de sa connexion : rien ne permet de le reconnaître au retour.',
    'config.reglage-s-lu-s-dans': '{v1} reglage(s) lu(s) dans {v2}.',
    'config.n-est-pas-un-nombre': '{v1} = « {v2} » n\'est pas un nombre, on garde {v3}.',
    'config.est-hors-des-bornes-ramene': '{v1} = {v2} est hors des bornes [{v3}, {v4}], ramene a {v5}.',
    'config.serveur-voyage': 'Serveur Voyage',
    'evenements.une-alarme-sonne': 'Une alarme sonne.',
    'evenements.fait': '{v1} fait « {v2} ».',
    'evenements.marque-un-point': '{v1} marque un point.',
    'evenements.est-tombe': '{v1} est tombé.',
    'http.publication-fermee-monde-motdepasse-n': 'publication fermée : MONDE_MOTDEPASSE n’est pas défini',
    'http.mot-de-passe-du-monde': 'mot de passe du monde refusé',
    'http.un-nouveau-monde-a-ete': 'Un nouveau monde a été publié : « {v1} ».',
    'http.aucun-monde-publie': 'aucun monde publié',
    'http.tcp': 'TCP : {v1}',
    'identite.identites-non-enregistrees': 'identités non enregistrées : {v1}',
    'inventaire.coffre-commun-espece-s-d': 'coffre commun : {v1} espèce(s) d’objet.',
    'inventaire.coffre-non-enregistre': 'coffre non enregistré : {v1}',
    'moderation.definitif': 'définitif',
    'moderation.sanction-s-en-vigueur': '{v1} sanction(s) en vigueur.',
    'moderation.sanctions-non-enregistrees': 'sanctions non enregistrées : {v1}',
    'moderation.identite': 'identité',
    'percage.le-point-de-rendez-vous': 'le point de rendez-vous est plein ; réessaie dans une minute.',
    'percage.ce-billet-n-existe-plus': 'ce billet n’existe plus (la partie est fermée, ou le billet a expiré).',
    'percage.percage-rendezvous-adresse-illisible-attendu': 'perçage : RENDEZVOUS_ADRESSE illisible (attendu « hôte:port »).',
    'percage.percage-annonce-vers': 'perçage : annonce vers {v1}:{v2}',
    'percage.percage-billet-c-est-ce': 'perçage : billet « {v1} » — c’est ce que tes amis saisissent.',
    'percage.percage-refuse-par-le-rendez': 'perçage refusé par le rendez-vous : {v1}',
    'permissions.tu-n-as-pas-le': 'Tu n’as pas le droit de changer les rôles.',
    'permissions.role-inconnu-au-choix': 'Rôle inconnu. Au choix : {v1}.',
    'permissions.tu-ne-peux-pas-donner': 'Tu ne peux pas donner un rôle égal ou supérieur au tien.',
    'permissions.cette-identite-est-inconnue-du': 'Cette identité est inconnue du serveur.',
    'rendezvous-seul.envoi-vers-refuse': 'envoi vers {v1}:{v2} refusé : {v3}',
    'rendezvous-seul.la-prise-a-lache': 'la prise a lâché : {v1}',
    'rendezvous-seul.a-l-ecoute-sur-en': 'à l\'écoute sur {v1}:{v2} en UDP',
    'rendezvous-seul.adresse-publique-annoncee': 'adresse publique annoncée : {v1}',
    'rendezvous-seul.cette-adresse-est-privee-personne': '⚠️ cette adresse est privée : personne ne pourra venir de l’extérieur.',
    'rendezvous-seul.arret-demande-les-hotes-se': 'arrêt demandé — les hôtes se réannonceront tout seuls.',
    'rendezvous.point-de-rendez-vous-actif': 'point de rendez-vous actif : les hôtes derrière une box peuvent s’y annoncer.',
    'ressources.ressources-chargee-s': 'ressources : {v1} chargée(s){v2}.',
    'ressources.fichier-d-entree-hors-du': 'fichier d’entrée hors du dossier',
    'ressources.fichier-d-entree-trop-gros': 'fichier d’entrée trop gros',
    'ressources.ressource-v-chargee': 'ressource « {v1} » v{v2} chargée.',
    'ressources.ressource-refusee': 'ressource « {v1} » refusée : {v2}',
    'ressources.evenement-inconnu': 'événement inconnu : {v1}',
    'ressources.il-faut-une-fonction-faire': 'il faut une fonction « faire »',
    'ressources.ressource-a-echoue-sur': 'ressource « {v1} » a échoué sur « {v2} » : {v3}',
    'ressources.ressource-ecoute-desactivee': 'ressource « {v1} » : écoute « {v2} » désactivée.',
    'sauvegardes.mot-de-passe-du-monde': 'mot de passe du monde lu dans donnees/motdepasse-monde.txt.',
    'sauvegardes.fiche-de-monde-sans-archive': 'fiche de monde sans archive : ignoree.',
    'sauvegardes.ce-n-est-pas-une': 'ce n’est pas une archive zip',
    'sauvegardes.hote': 'hôte',
    'sauvegardes.monde-publie-par-ko': 'monde « {v1} » publié par {v2} ({v3} ko).',
    'sauvegardes.aucun-monde-precedent': 'aucun monde précédent',
    'sauvegardes.retour-au-monde-precedent': 'retour au monde précédent « {v1} ».',
    'sauvegardes.point-de-rendez-vous-pose': 'point de rendez-vous posé par {v1}.',
    'sauvegardes.impossible-d-ecrire-les-positions': 'impossible d’écrire les positions : {v1}',
    'server.relais': 'relais {v1} — {v2}',
    'server.envoi-vers': 'envoi vers {v1}:{v2} — {v3}',
    'server.depose-dans-le-coffre-commun': '{v1} dépose {v2} {v3} dans le coffre commun.',
    'server.prend-dans-le-coffre-commun': '{v1} prend {v2} {v3} dans le coffre commun.',
    'server.revient-au-coffre': '{v1} {v2} revient au coffre.',
    'server.depart': 'départ',
    'server.tu-ne-peux-pas-parler': 'Tu ne peux pas parler sur ce serveur.',
    'server.tu-ne-peux-pas-parler-2': 'Tu ne peux pas parler pour le moment.',
    'server.personne-de-ce-nom-en': 'Personne de ce nom en jeu.',
    'server.tu-n-es-dans-aucune': 'Tu n’es dans aucune équipe.',
    'server.personne-n-est-assez-pres': 'Personne n’est assez près pour t’entendre.',
    'server.bienvenue-sur-tape-aide-pour': 'Bienvenue sur {v1}. Tape /aide pour les commandes.',
    'server.mot-du-jour': 'Mot du jour : {v1}',
    'server.udp': 'UDP : {v1}',
    'server.v-protocole-min': '{v1} — v{v2}, protocole {v3} (min {v4})',
    'server.places-instantanes-s': '{v1} places, {v2} instantanés/s{v3}',
    'server.percage-actif-vers': 'perçage actif vers {v1}',
    'server.point-de-rendez-vous-actif': 'point de rendez-vous actif sur ce port.',
    'server.cycle-jour-nuit-min-de': 'cycle jour/nuit : {v1} min de jeu par minute réelle',
    'server.proprietaire-s-declare-s-par': '{v1} propriétaire(s) déclaré(s) par empreinte.',
    'server.tcp': 'TCP {v1} : {v2}',
    'server.etat-non-enregistre': 'état non enregistré : {v1}',
    'server.le-serveur-s-arrete': 'Le serveur s’arrête.',
    'server.arrete': 'Arrêté.',
    'server.signal-recu': 'Signal {v1} reçu.',
    'server.arret-demande-par-la-console': 'Arrêt demandé par la console.',
    'server.promesse-rejetee': 'promesse rejetée : {v1}',
    'temps.jour': 'Jour {v1}.',
    'temps.la-meteo-passe-a': 'La météo passe à « {v1} ».',
    'percage.aveugle': 'ce point de rendez-vous ne voit pas les vraies adresses de ses visiteurs — il est lui-même derrière un tunnel ou un proxy. Le perçage est impossible par ce chemin : il faut un autre point de rendez-vous, ou rediriger un port sur ta box.',
    'percage.relais-ouvert': 'perçage impossible pour un joueur : il passe par le relais du rendez-vous (session {v1}). Sa latence sera plus haute.',
    'percage.symetrique': 'perçage : ta box change de port à chaque envoi (NAT symétrique). Tes amis ne pourront pas entrer sans redirection de port.',
    'rendezvous.aveugle': 'rendez-vous désactivé : ce serveur est annoncé public mais voit ses visiteurs arriver d’une adresse privée. Quelque chose réécrit la source en chemin (tunnel, proxy, NAT du fournisseur) : les adresses apprises ici seraient inutilisables. Il faut un point de rendez-vous joint en direct.',
    'rendezvous-seul.sans-adresse': '⚠️ ADRESSE_PUBLIQUE n’est pas donnée : le garde-fou est désarmé. Si cette machine passe un jour derrière un proxy qui masque les sources, ce rendez-vous distribuera des adresses mortes sans le dire.',
    'rendezvous-seul.bulletin': 'debout {v1} s · {v2} billet(s) · {v3} perçage(s) · {v4} reçus, {v5} ignorés',
    'identite.connues-et-oubliees': '{v1} identité(s) connue(s) ({v2} oubliée(s), plus vues depuis un an).',
    'identite.connues': '{v1} identité(s) connue(s).',
  },

  en: {
    'server.ecoute-jeu': 'game: UDP {v1}:{v2}',
    'server.ecoute-monde': 'world and browser: TCP {v1}:{v2}',
    'server.transport': 'transport: {v1}',
    'cmd.cap.n': 'north',
    'cmd.cap.ne': 'north-east',
    'cmd.cap.e': 'east',
    'cmd.cap.se': 'south-east',
    'cmd.cap.s': 'south',
    'cmd.cap.so': 'south-west',
    'cmd.cap.o': 'west',
    'cmd.cap.no': 'north-west',
    'session.expulse-remplace': 'replaced by another connection',
    'session.reprise-ailleurs': 'identity taken over elsewhere',
    'session.te-voila-hote': 'You are now the host of the game.',
    'cmd.equipier-pret': '{v1} is ready ({v2}).',
    'cmd.equipier-plus-pret': '{v1} is no longer ready ({v2}).',
    'cmd.coffre-depot': '{v1} dropped {v2} {v3}',
    'cmd.coffre-retrait': '{v1} took {v2} {v3}',
    'cmd.dont-refusees': ', {v1} refused',
    'ressources.dont-refusees': ', {v1} refused',
    'session.remplace': '{v1} replaced by a new connection from the same identity.',
    'cmd.figee': 'frozen',
    'cmd.tick': 'tick {v1} ms (worst {v2})',
    'cmd.tick-na': 'tick N/A',
    'cmd.processeur': 'processor {v1}',
    'annuaire.annuaire-eteint-annuaire-1-et': 'directory: off (ANNUAIRE=1 and ANNUAIRE_URL to switch it on).',
    'annuaire.annuaire-injoignable-depuis-essais-on': 'directory unreachable for {v1} attempts ({v2}) — we will try again.',
    'annuaire.annuaire-de-nouveau-joignable': 'directory: reachable again.',
    'annuaire.annuaire-url-invalide': 'ANNUAIRE_URL invalid',
    'annuaire.http': 'HTTP {v1}',
    'annuaire.delai-depasse': 'timed out',
    'cmd.texte': '/{v1} — {v2}',
    'cmd.commandes-aide-commande-pour-le': 'Commands ({v1}): {v2} · /aide <command> for details',
    'cmd.ton-identite-ton-role-ton': 'your identity, your role, your play time',
    'cmd.role': '{v1} — role {v2}',
    'cmd.identite': 'identity {v1}',
    'cmd.anonyme-pas-d-identite-signee': 'anonymous (no signed identity)',
    'cmd.equipe': 'team {v1}',
    'cmd.serveur-v-protocole-min-transport': '{v1} — server v{v2}, protocol {v3} (min {v4}), transport {v5}',
    'cmd.qui-est-connecte': 'who is connected',
    'cmd.hote': 'host',
    'cmd.ms': '{v1}{v2} — {v3} ms',
    'cmd.tu-es-a': 'You are at {v1}, {v2}, {v3}.',
    'cmd.qui-est-autour-de-toi': 'who is around you [metres]',
    'cmd.personne-a-moins-de-m': 'Nobody within {v1} m.',
    'cmd.a-m': '{v1} at {v2} m',
    'cmd.tu-es-seul-en-jeu': 'You are alone in game.',
    'cmd.m': '{v1} — {v2} m, {v3}',
    'cmd.le-serveur-ne-retient-rien': 'The server is holding nothing right now.',
    'cmd.a-pose-le-point-de': '{v1} set the rally point.',
    'cmd.point-de-rendez-vous-oublie': 'Rally point forgotten.',
    'cmd.aucun-point-de-rendez-vous': 'No rally point. Type /rdv poser where you want the others to arrive.',
    'cmd.rendez-vous-pose-par-a': 'Rally point set by {v1} — {v2} m from you, {v3}. In game, F5 takes you there.',
    'cmd.poser-un-repere-ici-nom': 'set a marker here [name]',
    'cmd.impossible-trop-de-reperes-sur': 'Cannot: too many markers on this server.',
    'cmd.a-pose-le-repere-n': '{v1} set the marker “{v2}” (no.{v3}).',
    'cmd.la-liste-des-reperes': 'the list of markers',
    'cmd.aucun-repere-pour-l-instant': 'No markers yet. /marquer sets one.',
    'cmd.n-m': 'no.{v1} {v2} — {v3} m, {v4}',
    'cmd.les-gestes-ne-sont-pas': 'Gestures are not available on this server.',
    'cmd.au-choix': 'Choose from: {v1}.',
    'cmd.doucement-trop-de-gestes-d': 'Steady on: too many gestures at once.',
    'cmd.message-prive-nom-texte': 'private message <name> <text>',
    'cmd.donne-un-nom-et-un': 'Give a name and a message: /mp Alex meet me at the lighthouse',
    'cmd.personne-de-ce-nom-ou': 'Nobody by that name, or several match.',
    'cmd.tu-te-parles-deja-tout': 'You already talk to yourself.',
    'cmd.prive-a': '(private to {v1}) {v2}',
    'cmd.equipes-equipe-equipe-creer-nom': 'teams: /equipe, /equipe creer <name>, /equipe rejoindre <name>, /equipe quitter',
    'cmd.les-equipes-ne-sont-pas': 'Teams are not available on this server.',
    'cmd.aucune-equipe-equipe-creer-nom': 'No teams. /equipe creer <name> makes one.',
    'cmd.pret-s': '{v1} ({v2}): {v3} — {v4}/{v5} ready',
    'cmd.donne-un-nom-equipe-creer': 'Give a name: /equipe creer Lighthouse',
    'cmd.impossible-trop-d-equipes-ou': 'Cannot: too many teams, or empty name.',
    'cmd.cree-l-equipe': '{v1} creates the team “{v2}”.',
    'cmd.aucune-equipe-de-ce-nom': 'No team by that name. /equipe for the list.',
    'cmd.rejoint': '{v1} joins “{v2}”.',
    'cmd.tu-n-es-dans-aucune': 'You are not in any team.',
    'cmd.tu-quittes': 'You leave “{v1}”.',
    'cmd.au-choix-equipe-creer-rejoindre': 'Choose from: /equipe · creer · rejoindre · quitter',
    'cmd.se-declarer-pret-ou-plus': 'declare yourself ready, or not ready any more',
    'cmd.rejoins-une-equipe-d-abord': 'Join a team first: /equipe creer <name>',
    'cmd.toute-l-equipe-est-prete': 'The whole team “{v1}” is ready.',
    'cmd.objectifs-activite-activite-creer-titre': 'objectives: /activite, /activite creer <title> | <step> | <step>, /activite demarrer <no.>, /activite fait <no.> <step>',
    'cmd.les-activites-ne-sont-pas': 'Activities are not available on this server.',
    'cmd.aucune-activite-activite-creer-reparer': 'No activities. /activite creer Repair the generator | Find the part | Fit it',
    'cmd.donne-un-titre-activite-creer': 'Give a title: /activite creer Repair the generator | Find the part',
    'cmd.impossible-trop-d-activites-en': 'Cannot: too many activities under way.',
    'cmd.propose-n-etape-s-activite': '{v1} proposes “{v2}” (no.{v3}, {v4} step(s)). /activite demarrer {v5}',
    'cmd.aucune-activite-proposee-sous-ce': 'No activity proposed under that number.',
    'cmd.commence': '“{v1}” begins.',
    'cmd.rien-a-cocher-verifie-le': 'Nothing to tick off: check the activity number and the step number.',
    'cmd.est-terminee-bravo': '“{v1}” is finished. Well done.',
    'cmd.a-fait': '{v1} did “{v2}” ({v3}).',
    'cmd.aucune-activite-sous-ce-numero': 'No activity under that number.',
    'cmd.est-abandonnee': '“{v1}” is abandoned.',
    'cmd.au-choix-activite-creer-demarrer': 'Choose from: /activite · creer · demarrer · fait · finir',
    'cmd.le-coffre-commun-n-est': 'The shared chest is not available on this server.',
    'cmd.aucun-mouvement-pour-l-instant': 'No movement yet.',
    'cmd.le-coffre-commun-est-vide': 'The shared chest is empty. In game, F10 drops what you carry into it.',
    'cmd.ce-que-quelqu-un-porte': 'what someone is carrying <name>',
    'cmd.l-inventaire-n-est-pas': 'The inventory is not available on this server.',
    'cmd.n-a-rien-declare-son': '{v1} has declared nothing (their mod does not read the inventory yet).',
    'cmd.retirer-un-repere-n': 'remove a marker <no.>',
    'cmd.donne-le-numero-du-repere': 'Give the marker number: /effacer 3',
    'cmd.repere-n-retire': 'Marker no.{v1} removed.',
    'cmd.aucun-repere-n': 'No marker no.{v1}.',
    'cmd.changer-la-meteo-nom': 'change the weather <name>',
    'cmd.donne-une-meteo-meteo-orage': 'Give a weather: /meteo orage',
    'cmd.la-meteo-passe-a': 'The weather turns to “{v1}”.',
    'cmd.changer-l-heure-h-min': 'change the time <h> [min]',
    'cmd.donne-une-heure-entre-0': 'Give an hour between 0 and 23: /heure 21',
    'cmd.il-est-maintenant-h': 'It is now {v1}:{v2}.',
    'cmd.la-cadence-du-cycle-jour': 'the day/night cycle rate [game minutes per real minute]',
    'cmd.l-horloge-du-serveur-n': 'The server clock is not available.',
    'cmd.jour-h-cadence-meteo': 'Day {v1}, {v2}:{v3} — rate {v4}, weather {v5}.',
    'cmd.donne-un-nombre-entre-0': 'Give a number between 0 (frozen) and 240.',
    'cmd.l-horloge-est-figee': 'The clock is frozen.',
    'cmd.le-temps-avance-de-min': 'Time advances {v1} game min per real minute.',
    'cmd.le-mot-du-jour-vide': 'the message of the day (empty to clear it)',
    'cmd.impossible-d-enregistrer-le-mot': 'Could not save the message of the day.',
    'cmd.mot-du-jour-efface': 'Message of the day cleared.',
    'cmd.mot-du-jour': 'Message of the day: {v1}',
    'cmd.expulser-quelqu-un-nom-raison': 'kick someone <name> [reason]',
    'cmd.donne-un-nom-expulser-alex': 'Give a name: /expulser Alex',
    'cmd.tu-ne-peux-pas-t': 'You cannot kick yourself.',
    'cmd.tu-ne-peux-pas-agir': 'You cannot act on someone of equal or higher rank.',
    'cmd.expulse-par-un-responsable': 'kicked by a moderator',
    'cmd.expulse': 'kicked',
    'cmd.a-ete-expulse-il-peut': '{v1} was kicked. They can come straight back — /bannir {v2} 1h to make it stick.',
    'cmd.bannir-nom-duree-30m-2h': 'ban <name> [duration: 30m 2h 7j, empty = permanent] [reason]',
    'cmd.la-moderation-n-est-pas': 'Moderation is not available on this server.',
    'cmd.donne-un-nom-bannir-alex': 'Give a name: /bannir Alex 2h insults',
    'cmd.personne-de-ce-nom-en': 'Nobody by that name in game. To ban someone absent, give their fingerprint to /bannir-id.',
    'cmd.tu-ne-peux-pas-te': 'You cannot ban yourself.',
    'cmd.duree-illisible-exemples-30m-2h': 'Unreadable duration. Examples: 30m, 2h, 7j, or nothing for permanent.',
    'cmd.impossible-ni-identite-ni-adresse': 'Cannot: neither identity nor address to aim at.',
    'cmd.attention-une-adresse-change-et': ' — careful: an address changes and may be shared by several people',
    'cmd.banni-sur-son': '{v1} banned {v2} on their {v3}{v4}.',
    'cmd.donne-une-empreinte-une-adresse': 'Give a fingerprint, an address or a name: /debannir a1b2c3…',
    'cmd.bannissement-s-leve-s': '{v1} ban(s) lifted.',
    'cmd.rien-ne-correspond': 'Nothing matches.',
    'cmd.empecher-quelqu-un-de-parler': 'stop someone from talking <name> [duration]',
    'cmd.donne-un-nom-museler-alex': 'Give a name: /museler Alex 15m',
    'cmd.duree-illisible-exemples-15m-2h': 'Unreadable duration. Examples: 15m, 2h.',
    'cmd.tu-ne-peux-plus-parler': 'You can no longer talk ({v1}).',
    'cmd.ne-peut-plus-parler-2': '{v1} can no longer talk — {v2}.',
    'cmd.donne-un-nom-ou-une': 'Give a name or a fingerprint.',
    'cmd.silence-s-leve-s': '{v1} mute(s) lifted.',
    'cmd.aucune-sanction-en-vigueur': 'No sanction in force.',
    'cmd.texte-3': '{v1} {v2} ({v3}) — {v4}{v5}',
    'cmd.donner-un-role-nom-empreinte': 'give a role <name|fingerprint> <proprietaire|admin|moderateur|joueur|aucun>',
    'cmd.les-roles-ne-sont-pas': 'Roles are not available on this server.',
    'cmd.exemple-role-alex-moderateur': 'Example: /role Alex moderateur',
    'cmd.ce-joueur-n-a-pas': 'This player has no signed identity: no lasting role can be given.',
    'cmd.tu-es-maintenant': 'You are now {v1}.',
    'cmd.ton-role-a-ete-retire': 'Your role has been removed.',
    'cmd.est-maintenant': '{v1} is now {v2}.',
    'cmd.role-retire': 'Role removed.',
    'cmd.le-profil-de-quelqu-un': 'someone’s profile <name>',
    'cmd.les-profils-ne-sont-pas': 'Profiles are not available on this server.',
    'cmd.joue-en-anonyme-aucun-profil': '{v1} plays anonymously: no lasting profile.',
    'cmd.profil-introuvable': 'Profile not found.',
    'cmd.session-s-h-role': '{v1} [{v2}] — {v3} session(s), {v4} h, role {v5}{v6}',
    'cmd.toutes-les-places-de-joueur': 'All player slots are taken.',
    'cmd.revient-en-jeu': '{v1} comes back into play.',
    'cmd.tu-es-l-hote-passe': 'You are the host: hand over first (leave and come back, or wait for someone else to play).',
    'cmd.passe-spectateur': '{v1} becomes a spectator.',
    'cmd.l-etat-du-serveur-reseau': 'the server state: network, ticks, memory',
    'cmd.les-mesures-ne-sont-pas': 'Measurements are not available on this server.',
    'cmd.memoire-mo': 'memory {v1} MB',
    'cmd.reseau-ko-s': 'network {v1} ↓ / {v2} ↑ kB/s',
    'cmd.reseau-n-a': 'network N/A',
    'cmd.instantane': 'snapshot {v1}',
    'cmd.entites': 'entities {v1}',
    'cmd.creatures': 'creatures {v1}',
    'cmd.ce-que-le-mod-a': 'what the mod managed to do in game <name>',
    'cmd.n-a-encore-rien-signale': '{v1} has reported nothing yet.',
    'cmd.les-creatures-que-l-hote': 'the creatures the host sees',
    'cmd.le-suivi-des-creatures-n': 'Creature tracking is not available.',
    'cmd.aucune-creature-signalee-c-est': 'No creature reported. It is the host who reports them.',
    'cmd.le-systeme-de-ressources-n': 'The resource system is not available.',
    'cmd.ressource-s-rechargee-s': '{v1} resource(s) reloaded{v2}.',
    'cmd.aucune-ressource-installee': 'No resource installed.',
    'cmd.retenu': 'Held: {v1}. {v2}',
    'cmd.tu-n-as-pas-le': 'You are not allowed to do that.',
    'cmd.la-commande-a-echoue': 'The command failed: {v1}',
    'cmd.commande-inconnue-tape-aide': 'Unknown command: /{v1}. Type /aide.',
    'cmd.l-hote': 'the host',
    'cmd.un-moderateur': 'a moderator',
    'cmd.le-proprietaire': 'the owner',
    'cmd.cette-commande-est-reservee-a': 'This command is reserved for {v1} (you are {v2}).',
    'cmd.aide.aide': 'the list of commands',
    'cmd.aide.serveur': 'the server version and its transport',
    'cmd.aide.ou': 'your position',
    'cmd.aide.radar': 'everyone’s direction and distance (radar in text)',
    'cmd.aide.rdv': 'the rally point (/rdv poser to set it here)',
    'cmd.aide.coffre': 'the shared chest: /coffre, /coffre journal',
    'cmd.aide.debannir': 'lift a ban <fingerprint|address|name>',
    'cmd.aide.demuseler': 'give speech back <fingerprint|address|name>',
    'cmd.aide.sanctions': 'the list of bans and mutes',
    'cmd.aide.spectateur': 'become a spectator, or come back into play',
    'cmd.aide.ressources': 'the server resources: /ressources, /ressources recharger',
    'cmd.aide.transport': 'which path the packets take, and why not the others',
    'cmd.un-administrateur': 'an administrator',
    'cmd.aide.geste': 'make a gesture ({v1})',
    'cmd.sessions-heures': '{v1} session(s), {v2} h played',
    'cmd.banni-raison': 'banned: {v1}',
    'cmd.sans-raison-donnee': 'no reason given',
    'cmd.museler-session': '{v1} can no longer talk — {v2}. With no signed identity and behind a shared address, it only lasts for this connection: nothing lets us recognise them when they come back.',
    'config.reglage-s-lu-s-dans': '{v1} setting(s) read from {v2}.',
    'config.n-est-pas-un-nombre': '{v1} = “{v2}” is not a number, keeping {v3}.',
    'config.est-hors-des-bornes-ramene': '{v1} = {v2} is outside [{v3}, {v4}], brought back to {v5}.',
    'config.serveur-voyage': 'Voyage Server',
    'evenements.une-alarme-sonne': 'An alarm goes off.',
    'evenements.fait': '{v1} does “{v2}”.',
    'evenements.marque-un-point': '{v1} scores a point.',
    'evenements.est-tombe': '{v1} has fallen.',
    'http.publication-fermee-monde-motdepasse-n': 'publishing closed: MONDE_MOTDEPASSE is not set',
    'http.mot-de-passe-du-monde': 'world password refused',
    'http.un-nouveau-monde-a-ete': 'A new world has been published: “{v1}”.',
    'http.aucun-monde-publie': 'no world published',
    'http.tcp': 'TCP: {v1}',
    'identite.identites-non-enregistrees': 'identities not saved: {v1}',
    'inventaire.coffre-commun-espece-s-d': 'shared chest: {v1} kind(s) of item.',
    'inventaire.coffre-non-enregistre': 'chest not saved: {v1}',
    'moderation.definitif': 'permanent',
    'moderation.sanction-s-en-vigueur': '{v1} sanction(s) in force.',
    'moderation.sanctions-non-enregistrees': 'sanctions not saved: {v1}',
    'moderation.identite': 'identity',
    'percage.le-point-de-rendez-vous': 'the rendezvous point is full; try again in a minute.',
    'percage.ce-billet-n-existe-plus': 'this ticket no longer exists (the game is closed, or the ticket expired).',
    'percage.percage-rendezvous-adresse-illisible-attendu': 'hole punching: RENDEZVOUS_ADRESSE unreadable (expected “host:port”).',
    'percage.percage-annonce-vers': 'hole punching: announcing to {v1}:{v2}',
    'percage.percage-billet-c-est-ce': 'hole punching: ticket “{v1}” — that is what your friends type.',
    'percage.percage-refuse-par-le-rendez': 'hole punching refused by the rendezvous: {v1}',
    'permissions.tu-n-as-pas-le': 'You are not allowed to change roles.',
    'permissions.role-inconnu-au-choix': 'Unknown role. Choose from: {v1}.',
    'permissions.tu-ne-peux-pas-donner': 'You cannot give a role equal to or higher than your own.',
    'permissions.cette-identite-est-inconnue-du': 'This identity is unknown to the server.',
    'rendezvous-seul.envoi-vers-refuse': 'send to {v1}:{v2} refused: {v3}',
    'rendezvous-seul.la-prise-a-lache': 'the socket gave out: {v1}',
    'rendezvous-seul.a-l-ecoute-sur-en': 'listening on {v1}:{v2} over UDP',
    'rendezvous-seul.adresse-publique-annoncee': 'public address announced: {v1}',
    'rendezvous-seul.cette-adresse-est-privee-personne': '⚠️ this address is private: nobody will be able to come from outside.',
    'rendezvous-seul.arret-demande-les-hotes-se': 'shutdown requested — the hosts will re-announce themselves.',
    'rendezvous.point-de-rendez-vous-actif': 'rendezvous point active: hosts behind a router can announce themselves here.',
    'ressources.ressources-chargee-s': 'resources: {v1} loaded{v2}.',
    'ressources.fichier-d-entree-hors-du': 'entry file outside the folder',
    'ressources.fichier-d-entree-trop-gros': 'entry file too large',
    'ressources.ressource-v-chargee': 'resource “{v1}” v{v2} loaded.',
    'ressources.ressource-refusee': 'resource “{v1}” refused: {v2}',
    'ressources.evenement-inconnu': 'unknown event: {v1}',
    'ressources.il-faut-une-fonction-faire': 'a “faire” function is required',
    'ressources.ressource-a-echoue-sur': 'resource “{v1}” failed on “{v2}”: {v3}',
    'ressources.ressource-ecoute-desactivee': 'resource “{v1}”: listener “{v2}” disabled.',
    'sauvegardes.mot-de-passe-du-monde': 'world password read from donnees/motdepasse-monde.txt.',
    'sauvegardes.fiche-de-monde-sans-archive': 'world record with no archive: ignored.',
    'sauvegardes.ce-n-est-pas-une': 'this is not a zip archive',
    'sauvegardes.hote': 'host',
    'sauvegardes.monde-publie-par-ko': 'world “{v1}” published by {v2} ({v3} kB).',
    'sauvegardes.aucun-monde-precedent': 'no previous world',
    'sauvegardes.retour-au-monde-precedent': 'back to the previous world “{v1}”.',
    'sauvegardes.point-de-rendez-vous-pose': 'rally point set by {v1}.',
    'sauvegardes.impossible-d-ecrire-les-positions': 'could not write the positions: {v1}',
    'server.relais': 'relay {v1} — {v2}',
    'server.envoi-vers': 'send to {v1}:{v2} — {v3}',
    'server.depose-dans-le-coffre-commun': '{v1} drops {v2} {v3} into the shared chest.',
    'server.prend-dans-le-coffre-commun': '{v1} takes {v2} {v3} from the shared chest.',
    'server.revient-au-coffre': '{v1} {v2} goes back to the chest.',
    'server.depart': 'departure',
    'server.tu-ne-peux-pas-parler': 'You cannot talk on this server.',
    'server.tu-ne-peux-pas-parler-2': 'You cannot talk right now.',
    'server.personne-de-ce-nom-en': 'Nobody by that name in game.',
    'server.tu-n-es-dans-aucune': 'You are not in any team.',
    'server.personne-n-est-assez-pres': 'Nobody is close enough to hear you.',
    'server.bienvenue-sur-tape-aide-pour': 'Welcome to {v1}. Type /aide for the commands.',
    'server.mot-du-jour': 'Message of the day: {v1}',
    'server.udp': 'UDP: {v1}',
    'server.v-protocole-min': '{v1} — v{v2}, protocol {v3} (min {v4})',
    'server.places-instantanes-s': '{v1} slots, {v2} snapshots/s{v3}',
    'server.percage-actif-vers': 'hole punching active towards {v1}',
    'server.point-de-rendez-vous-actif': 'rendezvous point active on this port.',
    'server.cycle-jour-nuit-min-de': 'day/night cycle: {v1} game min per real minute',
    'server.proprietaire-s-declare-s-par': '{v1} owner(s) declared by fingerprint.',
    'server.tcp': 'TCP {v1}: {v2}',
    'server.etat-non-enregistre': 'state not saved: {v1}',
    'server.le-serveur-s-arrete': 'The server is shutting down.',
    'server.arrete': 'Stopped.',
    'server.signal-recu': 'Signal {v1} received.',
    'server.arret-demande-par-la-console': 'Shutdown requested from the console.',
    'server.promesse-rejetee': 'promise rejected: {v1}',
    'temps.jour': 'Day {v1}.',
    'temps.la-meteo-passe-a': 'The weather turns to “{v1}”.',
    'percage.aveugle': 'this rendezvous point cannot see its visitors’ real addresses — it is itself behind a tunnel or a proxy. Hole punching is impossible this way: you need another rendezvous point, or to forward a port on your router.',
    'percage.relais-ouvert': 'hole punching impossible for one player: they go through the rendezvous relay (session {v1}). Their latency will be higher.',
    'percage.symetrique': 'hole punching: your router changes port on every packet (symmetric NAT). Your friends will not be able to get in without port forwarding.',
    'rendezvous.aveugle': 'rendezvous disabled: this server is announced as public but sees its visitors arriving from a private address. Something is rewriting the source along the way (tunnel, proxy, carrier NAT): the addresses learned here would be useless. A rendezvous point must be reached directly.',
    'rendezvous-seul.sans-adresse': '⚠️ ADRESSE_PUBLIQUE is not given: the safeguard is disarmed. If this machine ever ends up behind a proxy that masks sources, this rendezvous will hand out dead addresses without saying so.',
    'rendezvous-seul.bulletin': 'up {v1} s · {v2} ticket(s) · {v3} punch(es) · {v4} received, {v5} ignored',
    'identite.connues-et-oubliees': '{v1} known identity(ies) ({v2} forgotten, unseen for a year).',
    'identite.connues': '{v1} known identity(ies).',
  },

  es: {
    'server.ecoute-jeu': 'juego: UDP {v1}:{v2}',
    'server.ecoute-monde': 'mundo y navegador: TCP {v1}:{v2}',
    'server.transport': 'transporte: {v1}',
    'cmd.cap.n': 'norte',
    'cmd.cap.ne': 'noreste',
    'cmd.cap.e': 'este',
    'cmd.cap.se': 'sureste',
    'cmd.cap.s': 'sur',
    'cmd.cap.so': 'suroeste',
    'cmd.cap.o': 'oeste',
    'cmd.cap.no': 'noroeste',
    'session.expulse-remplace': 'sustituido por otra conexión',
    'session.reprise-ailleurs': 'identidad retomada en otro sitio',
    'session.te-voila-hote': 'Ahora eres el anfitrión de la partida.',
    'cmd.equipier-pret': '{v1} está listo ({v2}).',
    'cmd.equipier-plus-pret': '{v1} ya no está listo ({v2}).',
    'cmd.coffre-depot': '{v1} dejó {v2} {v3}',
    'cmd.coffre-retrait': '{v1} cogió {v2} {v3}',
    'cmd.dont-refusees': ', {v1} rechazado(s)',
    'ressources.dont-refusees': ', {v1} rechazado(s)',
    'session.remplace': '{v1} sustituido por una nueva conexión de la misma identidad.',
    'cmd.figee': 'congelado',
    'cmd.tick': 'tick {v1} ms (peor {v2})',
    'cmd.tick-na': 'tick N/D',
    'cmd.processeur': 'procesador {v1}',
    'annuaire.annuaire-eteint-annuaire-1-et': 'directorio: apagado (ANNUAIRE=1 y ANNUAIRE_URL para encenderlo).',
    'annuaire.annuaire-injoignable-depuis-essais-on': 'directorio inalcanzable desde hace {v1} intentos ({v2}) — lo reintentaremos.',
    'annuaire.annuaire-de-nouveau-joignable': 'directorio: alcanzable de nuevo.',
    'annuaire.annuaire-url-invalide': 'ANNUAIRE_URL inválida',
    'annuaire.http': 'HTTP {v1}',
    'annuaire.delai-depasse': 'tiempo agotado',
    'cmd.texte': '/{v1} — {v2}',
    'cmd.commandes-aide-commande-pour-le': 'Comandos ({v1}): {v2} · /aide <comando> para el detalle',
    'cmd.ton-identite-ton-role-ton': 'tu identidad, tu rol, tu tiempo de juego',
    'cmd.role': '{v1} — rol {v2}',
    'cmd.identite': 'identidad {v1}',
    'cmd.anonyme-pas-d-identite-signee': 'anónimo (sin identidad firmada)',
    'cmd.equipe': 'equipo {v1}',
    'cmd.serveur-v-protocole-min-transport': '{v1} — servidor v{v2}, protocolo {v3} (mín {v4}), transporte {v5}',
    'cmd.qui-est-connecte': 'quién está conectado',
    'cmd.hote': 'anfitrión',
    'cmd.ms': '{v1}{v2} — {v3} ms',
    'cmd.tu-es-a': 'Estás en {v1}, {v2}, {v3}.',
    'cmd.qui-est-autour-de-toi': 'quién está a tu alrededor [metros]',
    'cmd.personne-a-moins-de-m': 'Nadie a menos de {v1} m.',
    'cmd.a-m': '{v1} a {v2} m',
    'cmd.tu-es-seul-en-jeu': 'Estás solo en la partida.',
    'cmd.m': '{v1} — {v2} m, {v3}',
    'cmd.le-serveur-ne-retient-rien': 'El servidor no guarda nada por ahora.',
    'cmd.a-pose-le-point-de': '{v1} ha puesto el punto de encuentro.',
    'cmd.point-de-rendez-vous-oublie': 'Punto de encuentro olvidado.',
    'cmd.aucun-point-de-rendez-vous': 'Sin punto de encuentro. Escribe /rdv poser donde quieras que lleguen los demás.',
    'cmd.rendez-vous-pose-par-a': 'Punto de encuentro puesto por {v1} — a {v2} m de ti, {v3}. En el juego, F5 te lleva allí.',
    'cmd.poser-un-repere-ici-nom': 'poner una marca aquí [nombre]',
    'cmd.impossible-trop-de-reperes-sur': 'Imposible: demasiadas marcas en este servidor.',
    'cmd.a-pose-le-repere-n': '{v1} puso la marca «{v2}» (n.º{v3}).',
    'cmd.la-liste-des-reperes': 'la lista de marcas',
    'cmd.aucun-repere-pour-l-instant': 'Ninguna marca por ahora. /marquer pone una.',
    'cmd.n-m': 'n.º{v1} {v2} — {v3} m, {v4}',
    'cmd.les-gestes-ne-sont-pas': 'Los gestos no están disponibles en este servidor.',
    'cmd.au-choix': 'A elegir: {v1}.',
    'cmd.doucement-trop-de-gestes-d': 'Despacio: demasiados gestos de golpe.',
    'cmd.message-prive-nom-texte': 'mensaje privado <nombre> <texto>',
    'cmd.donne-un-nom-et-un': 'Da un nombre y un mensaje: /mp Alex nos vemos en el faro',
    'cmd.personne-de-ce-nom-ou': 'Nadie con ese nombre, o varios coinciden.',
    'cmd.tu-te-parles-deja-tout': 'Ya hablas contigo mismo.',
    'cmd.prive-a': '(privado a {v1}) {v2}',
    'cmd.equipes-equipe-equipe-creer-nom': 'equipos: /equipe, /equipe creer <nombre>, /equipe rejoindre <nombre>, /equipe quitter',
    'cmd.les-equipes-ne-sont-pas': 'Los equipos no están disponibles en este servidor.',
    'cmd.aucune-equipe-equipe-creer-nom': 'Ningún equipo. /equipe creer <nombre> crea uno.',
    'cmd.pret-s': '{v1} ({v2}): {v3} — {v4}/{v5} listo(s)',
    'cmd.donne-un-nom-equipe-creer': 'Da un nombre: /equipe creer Faro',
    'cmd.impossible-trop-d-equipes-ou': 'Imposible: demasiados equipos, o nombre vacío.',
    'cmd.cree-l-equipe': '{v1} crea el equipo «{v2}».',
    'cmd.aucune-equipe-de-ce-nom': 'Ningún equipo con ese nombre. /equipe para la lista.',
    'cmd.rejoint': '{v1} se une a «{v2}».',
    'cmd.tu-n-es-dans-aucune': 'No estás en ningún equipo.',
    'cmd.tu-quittes': 'Dejas «{v1}».',
    'cmd.au-choix-equipe-creer-rejoindre': 'A elegir: /equipe · creer · rejoindre · quitter',
    'cmd.se-declarer-pret-ou-plus': 'declararte listo, o ya no listo',
    'cmd.rejoins-une-equipe-d-abord': 'Únete a un equipo primero: /equipe creer <nombre>',
    'cmd.toute-l-equipe-est-prete': 'Todo el equipo «{v1}» está listo.',
    'cmd.objectifs-activite-activite-creer-titre': 'objetivos: /activite, /activite creer <título> | <paso> | <paso>, /activite demarrer <n.º>, /activite fait <n.º> <paso>',
    'cmd.les-activites-ne-sont-pas': 'Las actividades no están disponibles en este servidor.',
    'cmd.aucune-activite-activite-creer-reparer': 'Ninguna actividad. /activite creer Reparar el generador | Encontrar la pieza | Colocarla',
    'cmd.donne-un-titre-activite-creer': 'Da un título: /activite creer Reparar el generador | Encontrar la pieza',
    'cmd.impossible-trop-d-activites-en': 'Imposible: demasiadas actividades en curso.',
    'cmd.propose-n-etape-s-activite': '{v1} propone «{v2}» (n.º{v3}, {v4} paso(s)). /activite demarrer {v5}',
    'cmd.aucune-activite-proposee-sous-ce': 'Ninguna actividad propuesta con ese número.',
    'cmd.commence': '«{v1}» comienza.',
    'cmd.rien-a-cocher-verifie-le': 'Nada que marcar: comprueba el número de actividad y el del paso.',
    'cmd.est-terminee-bravo': '«{v1}» ha terminado. Bien hecho.',
    'cmd.a-fait': '{v1} hizo «{v2}» ({v3}).',
    'cmd.aucune-activite-sous-ce-numero': 'Ninguna actividad con ese número.',
    'cmd.est-abandonnee': '«{v1}» queda abandonada.',
    'cmd.au-choix-activite-creer-demarrer': 'A elegir: /activite · creer · demarrer · fait · finir',
    'cmd.le-coffre-commun-n-est': 'El cofre común no está disponible en este servidor.',
    'cmd.aucun-mouvement-pour-l-instant': 'Ningún movimiento por ahora.',
    'cmd.le-coffre-commun-est-vide': 'El cofre común está vacío. En el juego, F10 deja dentro lo que llevas.',
    'cmd.ce-que-quelqu-un-porte': 'lo que alguien lleva <nombre>',
    'cmd.l-inventaire-n-est-pas': 'El inventario no está disponible en este servidor.',
    'cmd.n-a-rien-declare-son': '{v1} no ha declarado nada (su mod aún no lee el inventario).',
    'cmd.retirer-un-repere-n': 'quitar una marca <n.º>',
    'cmd.donne-le-numero-du-repere': 'Da el número de la marca: /effacer 3',
    'cmd.repere-n-retire': 'Marca n.º{v1} quitada.',
    'cmd.aucun-repere-n': 'Ninguna marca n.º{v1}.',
    'cmd.changer-la-meteo-nom': 'cambiar el tiempo <nombre>',
    'cmd.donne-une-meteo-meteo-orage': 'Da un tiempo: /meteo orage',
    'cmd.la-meteo-passe-a': 'El tiempo pasa a «{v1}».',
    'cmd.changer-l-heure-h-min': 'cambiar la hora <h> [min]',
    'cmd.donne-une-heure-entre-0': 'Da una hora entre 0 y 23: /heure 21',
    'cmd.il-est-maintenant-h': 'Ahora son las {v1}:{v2}.',
    'cmd.la-cadence-du-cycle-jour': 'el ritmo del ciclo día/noche [minutos de juego por minuto real]',
    'cmd.l-horloge-du-serveur-n': 'El reloj del servidor no está disponible.',
    'cmd.jour-h-cadence-meteo': 'Día {v1}, {v2}:{v3} — ritmo {v4}, tiempo {v5}.',
    'cmd.donne-un-nombre-entre-0': 'Da un número entre 0 (congelado) y 240.',
    'cmd.l-horloge-est-figee': 'El reloj está congelado.',
    'cmd.le-temps-avance-de-min': 'El tiempo avanza {v1} min de juego por minuto real.',
    'cmd.le-mot-du-jour-vide': 'el mensaje del día (vacío para borrarlo)',
    'cmd.impossible-d-enregistrer-le-mot': 'Imposible guardar el mensaje del día.',
    'cmd.mot-du-jour-efface': 'Mensaje del día borrado.',
    'cmd.mot-du-jour': 'Mensaje del día: {v1}',
    'cmd.expulser-quelqu-un-nom-raison': 'expulsar a alguien <nombre> [motivo]',
    'cmd.donne-un-nom-expulser-alex': 'Da un nombre: /expulser Alex',
    'cmd.tu-ne-peux-pas-t': 'No puedes expulsarte a ti mismo.',
    'cmd.tu-ne-peux-pas-agir': 'No puedes actuar sobre alguien de rango igual o superior.',
    'cmd.expulse-par-un-responsable': 'expulsado por un responsable',
    'cmd.expulse': 'expulsado',
    'cmd.a-ete-expulse-il-peut': '{v1} ha sido expulsado. Puede volver enseguida — /bannir {v2} 1h para que dure.',
    'cmd.bannir-nom-duree-30m-2h': 'banear <nombre> [duración: 30m 2h 7j, vacío = definitivo] [motivo]',
    'cmd.la-moderation-n-est-pas': 'La moderación no está disponible en este servidor.',
    'cmd.donne-un-nom-bannir-alex': 'Da un nombre: /bannir Alex 2h insultos',
    'cmd.personne-de-ce-nom-en': 'Nadie con ese nombre en la partida. Para banear a un ausente, da su huella a /bannir-id.',
    'cmd.tu-ne-peux-pas-te': 'No puedes banearte a ti mismo.',
    'cmd.duree-illisible-exemples-30m-2h': 'Duración ilegible. Ejemplos: 30m, 2h, 7j, o nada para definitivo.',
    'cmd.impossible-ni-identite-ni-adresse': 'Imposible: ni identidad ni dirección a la que apuntar.',
    'cmd.attention-une-adresse-change-et': ' — atención: una dirección cambia y puede estar compartida por varias personas',
    'cmd.banni-sur-son': '{v1} baneado {v2} por su {v3}{v4}.',
    'cmd.donne-une-empreinte-une-adresse': 'Da una huella, una dirección o un nombre: /debannir a1b2c3…',
    'cmd.bannissement-s-leve-s': '{v1} baneo(s) levantado(s).',
    'cmd.rien-ne-correspond': 'Nada coincide.',
    'cmd.empecher-quelqu-un-de-parler': 'impedir que alguien hable <nombre> [duración]',
    'cmd.donne-un-nom-museler-alex': 'Da un nombre: /museler Alex 15m',
    'cmd.duree-illisible-exemples-15m-2h': 'Duración ilegible. Ejemplos: 15m, 2h.',
    'cmd.tu-ne-peux-plus-parler': 'Ya no puedes hablar ({v1}).',
    'cmd.ne-peut-plus-parler-2': '{v1} ya no puede hablar — {v2}.',
    'cmd.donne-un-nom-ou-une': 'Da un nombre o una huella.',
    'cmd.silence-s-leve-s': '{v1} silencio(s) levantado(s).',
    'cmd.aucune-sanction-en-vigueur': 'Ninguna sanción en vigor.',
    'cmd.texte-3': '{v1} {v2} ({v3}) — {v4}{v5}',
    'cmd.donner-un-role-nom-empreinte': 'dar un rol <nombre|huella> <proprietaire|admin|moderateur|joueur|aucun>',
    'cmd.les-roles-ne-sont-pas': 'Los roles no están disponibles en este servidor.',
    'cmd.exemple-role-alex-moderateur': 'Ejemplo: /role Alex moderateur',
    'cmd.ce-joueur-n-a-pas': 'Este jugador no tiene identidad firmada: no se le puede dar un rol duradero.',
    'cmd.tu-es-maintenant': 'Ahora eres {v1}.',
    'cmd.ton-role-a-ete-retire': 'Te han quitado el rol.',
    'cmd.est-maintenant': '{v1} es ahora {v2}.',
    'cmd.role-retire': 'Rol quitado.',
    'cmd.le-profil-de-quelqu-un': 'el perfil de alguien <nombre>',
    'cmd.les-profils-ne-sont-pas': 'Los perfiles no están disponibles en este servidor.',
    'cmd.joue-en-anonyme-aucun-profil': '{v1} juega en anónimo: ningún perfil duradero.',
    'cmd.profil-introuvable': 'Perfil no encontrado.',
    'cmd.session-s-h-role': '{v1} [{v2}] — {v3} sesión(es), {v4} h, rol {v5}{v6}',
    'cmd.toutes-les-places-de-joueur': 'Todas las plazas de jugador están ocupadas.',
    'cmd.revient-en-jeu': '{v1} vuelve a la partida.',
    'cmd.tu-es-l-hote-passe': 'Eres el anfitrión: pasa el testigo antes (sal y vuelve, o espera a que juegue otro).',
    'cmd.passe-spectateur': '{v1} pasa a espectador.',
    'cmd.l-etat-du-serveur-reseau': 'el estado del servidor: red, ticks, memoria',
    'cmd.les-mesures-ne-sont-pas': 'Las mediciones no están disponibles en este servidor.',
    'cmd.memoire-mo': 'memoria {v1} MB',
    'cmd.reseau-ko-s': 'red {v1} ↓ / {v2} ↑ kB/s',
    'cmd.reseau-n-a': 'red N/D',
    'cmd.instantane': 'instantánea {v1}',
    'cmd.entites': 'entidades {v1}',
    'cmd.creatures': 'criaturas {v1}',
    'cmd.ce-que-le-mod-a': 'lo que el mod ha conseguido hacer en el juego <nombre>',
    'cmd.n-a-encore-rien-signale': '{v1} aún no ha informado de nada.',
    'cmd.les-creatures-que-l-hote': 'las criaturas que ve el anfitrión',
    'cmd.le-suivi-des-creatures-n': 'El seguimiento de criaturas no está disponible.',
    'cmd.aucune-creature-signalee-c-est': 'Ninguna criatura informada. Es el anfitrión quien las informa.',
    'cmd.le-systeme-de-ressources-n': 'El sistema de recursos no está disponible.',
    'cmd.ressource-s-rechargee-s': '{v1} recurso(s) recargado(s){v2}.',
    'cmd.aucune-ressource-installee': 'Ningún recurso instalado.',
    'cmd.retenu': 'Retenido: {v1}. {v2}',
    'cmd.tu-n-as-pas-le': 'No tienes derecho a hacer eso.',
    'cmd.la-commande-a-echoue': 'El comando ha fallado: {v1}',
    'cmd.commande-inconnue-tape-aide': 'Comando desconocido: /{v1}. Escribe /aide.',
    'cmd.l-hote': 'el anfitrión',
    'cmd.un-moderateur': 'un moderador',
    'cmd.le-proprietaire': 'el propietario',
    'cmd.cette-commande-est-reservee-a': 'Este comando está reservado a {v1} (tú eres {v2}).',
    'cmd.aide.aide': 'la lista de comandos',
    'cmd.aide.serveur': 'la versión del servidor y su transporte',
    'cmd.aide.ou': 'tu posición',
    'cmd.aide.radar': 'la dirección y la distancia de cada uno (radar en texto)',
    'cmd.aide.rdv': 'el punto de encuentro (/rdv poser para fijarlo aquí)',
    'cmd.aide.coffre': 'el cofre común: /coffre, /coffre journal',
    'cmd.aide.debannir': 'levantar un baneo <huella|dirección|nombre>',
    'cmd.aide.demuseler': 'devolver la palabra <huella|dirección|nombre>',
    'cmd.aide.sanctions': 'la lista de baneos y silencios',
    'cmd.aide.spectateur': 'pasar a espectador, o volver a jugar',
    'cmd.aide.ressources': 'los recursos del servidor: /ressources, /ressources recharger',
    'cmd.aide.transport': 'por qué camino pasan los paquetes, y por qué no los otros',
    'cmd.un-administrateur': 'un administrador',
    'cmd.aide.geste': 'hacer un gesto ({v1})',
    'cmd.sessions-heures': '{v1} sesión(es), {v2} h de juego',
    'cmd.banni-raison': 'baneado: {v1}',
    'cmd.sans-raison-donnee': 'sin motivo indicado',
    'cmd.museler-session': '{v1} ya no puede hablar — {v2}. Sin identidad firmada y tras una dirección compartida, solo dura lo que dure su conexión: nada permite reconocerlo cuando vuelva.',
    'config.reglage-s-lu-s-dans': '{v1} ajuste(s) leído(s) en {v2}.',
    'config.n-est-pas-un-nombre': '{v1} = «{v2}» no es un número, se mantiene {v3}.',
    'config.est-hors-des-bornes-ramene': '{v1} = {v2} está fuera de [{v3}, {v4}], ajustado a {v5}.',
    'config.serveur-voyage': 'Servidor Voyage',
    'evenements.une-alarme-sonne': 'Suena una alarma.',
    'evenements.fait': '{v1} hace «{v2}».',
    'evenements.marque-un-point': '{v1} marca un punto.',
    'evenements.est-tombe': '{v1} ha caído.',
    'http.publication-fermee-monde-motdepasse-n': 'publicación cerrada: MONDE_MOTDEPASSE no está definido',
    'http.mot-de-passe-du-monde': 'contraseña del mundo rechazada',
    'http.un-nouveau-monde-a-ete': 'Se ha publicado un mundo nuevo: «{v1}».',
    'http.aucun-monde-publie': 'ningún mundo publicado',
    'http.tcp': 'TCP: {v1}',
    'identite.identites-non-enregistrees': 'identidades no guardadas: {v1}',
    'inventaire.coffre-commun-espece-s-d': 'cofre común: {v1} tipo(s) de objeto.',
    'inventaire.coffre-non-enregistre': 'cofre no guardado: {v1}',
    'moderation.definitif': 'definitivo',
    'moderation.sanction-s-en-vigueur': '{v1} sanción(es) en vigor.',
    'moderation.sanctions-non-enregistrees': 'sanciones no guardadas: {v1}',
    'moderation.identite': 'identidad',
    'percage.le-point-de-rendez-vous': 'el punto de encuentro está lleno; inténtalo dentro de un minuto.',
    'percage.ce-billet-n-existe-plus': 'este billete ya no existe (la partida está cerrada, o el billete caducó).',
    'percage.percage-rendezvous-adresse-illisible-attendu': 'perforación: RENDEZVOUS_ADRESSE ilegible (se esperaba «host:puerto»).',
    'percage.percage-annonce-vers': 'perforación: anunciando a {v1}:{v2}',
    'percage.percage-billet-c-est-ce': 'perforación: billete «{v1}» — eso es lo que escriben tus amigos.',
    'percage.percage-refuse-par-le-rendez': 'perforación rechazada por el punto de encuentro: {v1}',
    'permissions.tu-n-as-pas-le': 'No tienes derecho a cambiar los roles.',
    'permissions.role-inconnu-au-choix': 'Rol desconocido. A elegir: {v1}.',
    'permissions.tu-ne-peux-pas-donner': 'No puedes dar un rol igual o superior al tuyo.',
    'permissions.cette-identite-est-inconnue-du': 'Esta identidad es desconocida para el servidor.',
    'rendezvous-seul.envoi-vers-refuse': 'envío a {v1}:{v2} rechazado: {v3}',
    'rendezvous-seul.la-prise-a-lache': 'el socket ha fallado: {v1}',
    'rendezvous-seul.a-l-ecoute-sur-en': 'escuchando en {v1}:{v2} por UDP',
    'rendezvous-seul.adresse-publique-annoncee': 'dirección pública anunciada: {v1}',
    'rendezvous-seul.cette-adresse-est-privee-personne': '⚠️ esta dirección es privada: nadie podrá venir desde fuera.',
    'rendezvous-seul.arret-demande-les-hotes-se': 'parada solicitada — los anfitriones se volverán a anunciar solos.',
    'rendezvous.point-de-rendez-vous-actif': 'punto de encuentro activo: los anfitriones tras un router pueden anunciarse aquí.',
    'ressources.ressources-chargee-s': 'recursos: {v1} cargado(s){v2}.',
    'ressources.fichier-d-entree-hors-du': 'archivo de entrada fuera de la carpeta',
    'ressources.fichier-d-entree-trop-gros': 'archivo de entrada demasiado grande',
    'ressources.ressource-v-chargee': 'recurso «{v1}» v{v2} cargado.',
    'ressources.ressource-refusee': 'recurso «{v1}» rechazado: {v2}',
    'ressources.evenement-inconnu': 'evento desconocido: {v1}',
    'ressources.il-faut-une-fonction-faire': 'hace falta una función «faire»',
    'ressources.ressource-a-echoue-sur': 'el recurso «{v1}» falló en «{v2}»: {v3}',
    'ressources.ressource-ecoute-desactivee': 'recurso «{v1}»: escucha «{v2}» desactivada.',
    'sauvegardes.mot-de-passe-du-monde': 'contraseña del mundo leída en donnees/motdepasse-monde.txt.',
    'sauvegardes.fiche-de-monde-sans-archive': 'ficha de mundo sin archivo: ignorada.',
    'sauvegardes.ce-n-est-pas-une': 'esto no es un archivo zip',
    'sauvegardes.hote': 'anfitrión',
    'sauvegardes.monde-publie-par-ko': 'mundo «{v1}» publicado por {v2} ({v3} kB).',
    'sauvegardes.aucun-monde-precedent': 'ningún mundo anterior',
    'sauvegardes.retour-au-monde-precedent': 'vuelta al mundo anterior «{v1}».',
    'sauvegardes.point-de-rendez-vous-pose': 'punto de encuentro puesto por {v1}.',
    'sauvegardes.impossible-d-ecrire-les-positions': 'imposible escribir las posiciones: {v1}',
    'server.relais': 'relé {v1} — {v2}',
    'server.envoi-vers': 'envío a {v1}:{v2} — {v3}',
    'server.depose-dans-le-coffre-commun': '{v1} deja {v2} {v3} en el cofre común.',
    'server.prend-dans-le-coffre-commun': '{v1} coge {v2} {v3} del cofre común.',
    'server.revient-au-coffre': '{v1} {v2} vuelve al cofre.',
    'server.depart': 'salida',
    'server.tu-ne-peux-pas-parler': 'No puedes hablar en este servidor.',
    'server.tu-ne-peux-pas-parler-2': 'No puedes hablar ahora mismo.',
    'server.personne-de-ce-nom-en': 'Nadie con ese nombre en la partida.',
    'server.tu-n-es-dans-aucune': 'No estás en ningún equipo.',
    'server.personne-n-est-assez-pres': 'Nadie está lo bastante cerca para oírte.',
    'server.bienvenue-sur-tape-aide-pour': 'Bienvenido a {v1}. Escribe /aide para los comandos.',
    'server.mot-du-jour': 'Mensaje del día: {v1}',
    'server.udp': 'UDP: {v1}',
    'server.v-protocole-min': '{v1} — v{v2}, protocolo {v3} (mín {v4})',
    'server.places-instantanes-s': '{v1} plazas, {v2} instantáneas/s{v3}',
    'server.percage-actif-vers': 'perforación activa hacia {v1}',
    'server.point-de-rendez-vous-actif': 'punto de encuentro activo en este puerto.',
    'server.cycle-jour-nuit-min-de': 'ciclo día/noche: {v1} min de juego por minuto real',
    'server.proprietaire-s-declare-s-par': '{v1} propietario(s) declarado(s) por huella.',
    'server.tcp': 'TCP {v1}: {v2}',
    'server.etat-non-enregistre': 'estado no guardado: {v1}',
    'server.le-serveur-s-arrete': 'El servidor se detiene.',
    'server.arrete': 'Detenido.',
    'server.signal-recu': 'Señal {v1} recibida.',
    'server.arret-demande-par-la-console': 'Parada solicitada desde la consola.',
    'server.promesse-rejetee': 'promesa rechazada: {v1}',
    'temps.jour': 'Día {v1}.',
    'temps.la-meteo-passe-a': 'El tiempo pasa a «{v1}».',
    'percage.aveugle': 'este punto de encuentro no ve las direcciones reales de sus visitantes — está él mismo tras un túnel o un proxy. La perforación es imposible por ahí: hace falta otro punto de encuentro, o redirigir un puerto en tu router.',
    'percage.relais-ouvert': 'perforación imposible para un jugador: pasa por el relé del punto de encuentro (sesión {v1}). Su latencia será más alta.',
    'percage.symetrique': 'perforación: tu router cambia de puerto en cada envío (NAT simétrico). Tus amigos no podrán entrar sin redirigir un puerto.',
    'rendezvous.aveugle': 'punto de encuentro desactivado: este servidor se anuncia como público pero ve a sus visitantes llegar desde una dirección privada. Algo reescribe el origen por el camino (túnel, proxy, NAT del operador): las direcciones aprendidas aquí serían inservibles. Hace falta un punto de encuentro alcanzado directamente.',
    'rendezvous-seul.sans-adresse': '⚠️ ADRESSE_PUBLIQUE no está dada: la salvaguarda está desarmada. Si esta máquina acaba algún día tras un proxy que oculta los orígenes, este punto de encuentro repartirá direcciones muertas sin decirlo.',
    'rendezvous-seul.bulletin': 'en pie {v1} s · {v2} billete(s) · {v3} perforación(es) · {v4} recibidos, {v5} ignorados',
    'identite.connues-et-oubliees': '{v1} identidad(es) conocida(s) ({v2} olvidada(s), sin verse desde hace un año).',
    'identite.connues': '{v1} identidad(es) conocida(s).',
  },
}
