'use strict'

/**
 * ═══════════════════════════════════════════════════════════════════════════
 *  TROIS LANGUES
 * ═══════════════════════════════════════════════════════════════════════════
 *  ⚠️ CE FICHIER EST UN SCRIPT CLASSIQUE, PAS UN MODULE. Il partage donc sa
 *     portee avec `app.js` : un nom declare deux fois en `const` fait planter
 *     TOUT le script, et l'interface reste figee sans un mot d'erreur
 *     visible. D'ou le prefixe `LANGUES_` sur chaque nom d'ici.
 *
 *  ⚠️ LE FRANCAIS EST LA REFERENCE. Une cle absente d'une traduction retombe
 *     dessus plutot que d'afficher la cle brute a l'utilisateur.
 */

const LANGUES_TEXTES = {
  fr: {
    'appli.sousTitre': 'Coopération pour The Last Caretaker — Symbiose Héritage',
    'appli.pied': 'Projet indépendant — aucun fichier du jeu n’est distribué',
    'serv.public': 'annuaire public',
    'serv.ping': '{ms} ms',
    'serv.garder': 'Garder',
    'cre.titre': 'Les créatures',
    'cre.sousTitre': 'Ce que tu vois des requins, anges et essaims',
    'cre.detail':
      'Le jeu fait apparaître ses créatures chez chacun, séparément : rien ne relie ton requin à celui de ton ami. Le miroir masque les tiennes et affiche celles de l’hôte — c’est la seule façon de voir le même.',
    'cre.miroir': 'Celles de l’hôte (miroir)',
    'cre.annonce': 'Les miennes, et on m’annonce les siennes',
    'cre.rien': 'Les miennes seulement',
    'cre.note': 'En jeu, F2 bascule sans passer par ici — pratique si quelque chose cloche en pleine partie.',
    'serv.lien': 'Lien',
    'serv.lienCopie': 'Lien d’invitation copié — colle-le à tes amis.',
    'serv.administrer': 'Administrer',
    'serv.aucunFiltre': 'Aucun serveur ne passe tes filtres.',
    'adm.demandeCle': 'Clé d’administration de « {nom} ». Ce n’est PAS le mot de passe du serveur : c’est la clé ADMIN_CLE posée dans ses réglages.',
    'adm.invite': '{nom}\n\n{joueurs}\n\nUne commande à lancer ?',
    'inv.titre': 'Quelqu’un t’invite',
    'inv.adresse': 'Serveur {adresse}{protege}',
    'inv.billet': 'Billet {billet}{protege}',
    'inv.protege': ' — un mot de passe sera demandé',
    'inv.rejoindre': 'Rejoindre',
    'inv.ignorer': 'Ignorer',

    'filtre.titre': 'Filtrer la liste',
    'filtre.detail': 'Appliqué à ce que tu vois, sans rien redemander au réseau.',
    'filtre.enLigne': 'En ligne',
    'filtre.libres': 'Places libres',
    'filtre.ouverts': 'Sans mot de passe',

    'maj.titre': 'Mises à jour',
    'maj.inconnue': 'Version du lanceur inconnue',
    'maj.aJour': 'Lanceur {v} — à jour',
    'maj.disponible': 'Lanceur {v} — la {nouvelle} est sortie',
    'maj.echec': 'Impossible de vérifier ({raison})',
    'maj.lanceurDetail': 'On regarde, on ne télécharge rien tout seul. Un lanceur trop ancien se fait refuser par les serveurs.',
    'maj.verifier': 'Vérifier',
    'maj.telecharger': 'Ouvrir la page',
    'maj.installer': 'Télécharger et installer',
    'maj.enCours': 'Téléchargement… {pourcent} %',
    'maj.verifiee': 'Version {v} téléchargée, empreinte vérifiée.',
    'maj.fermeture': 'Le lanceur va se fermer pour laisser l’installeur travailler.',
    'err.archiveDouteuse': 'Archive refusée : elle contient « {nom} », qui n’est pas une sauvegarde. Rien n’a été extrait.',
    'err.majRien': 'Il n’y a rien de plus récent à installer.',
    'err.majPasPret': 'Rien n’a été téléchargé : relance la vérification.',
    'err.majNom': 'Le nom de fichier annoncé est refusé.',
    'err.majSansEmpreinte': 'Aucune empreinte publiée : on refuse d’installer un fichier qu’on ne peut pas vérifier.',
    'err.majEmpreinte': 'Le fichier reçu ne correspond pas à l’empreinte publiée. Rien n’a été installé.',
    'err.majServeurEnMarche': 'Arrête d’abord ton serveur : l’installeur fermerait la partie de tes joueurs.',
    'maj.jeuTitre': 'Le jeu',
    'maj.jeuInconnu': 'Version du jeu inconnue — indique son dossier dans l’onglet Installation.',
    'maj.jeuConnu': 'Build Steam {build}, inchangé depuis la dernière fois.',
    'maj.jeuChange': 'Le jeu a été mis à jour ({avant} → {build}). Le mod n’a pas encore été vérifié avec cette version : si quelque chose cloche, dis-le-nous.',
    'maj.jeuPremier': 'Build Steam {build} — on le retient pour détecter les prochaines mises à jour.',

    'sout.titre': 'Pack de soutien',
    'sout.sousTitre': 'Tout ce qu’il faut pour comprendre un problème',
    'sout.detail': 'Versions, journaux, diagnostics et empreintes, dans un fichier texte posé sur ton bureau.',
    'sout.fabriquer': 'Fabriquer',
    'sout.expurge': 'Les lignes pouvant contenir un mot de passe, une clé ou un jeton sont retirées — et leur retrait est écrit, pour que rien ne manque en silence.',
    'sout.fait': 'Pack écrit sur ton bureau : {nom}',

    'pl.titre': 'Les noms au-dessus des têtes',
    'pl.sousTitre': 'Ce que tu affiches sur les autres joueurs',
    'pl.detail': 'Ces réglages ne partent pas sur le réseau : ils ne décident que de ce que TOI tu vois.',
    'pl.noms': 'Nom',
    'pl.distance': 'Distance',
    'pl.ping': 'Ping',
    'pl.vie': 'Vie',
    'pl.porteeTitre': 'Jusqu’à quelle distance',
    'pl.porteeDetail': 'En mètres. Au-delà, la plaque disparaît plutôt que de devenir illisible.',

    'dbg.titre': 'Mode debug',
    'dbg.detail': 'Affiche en jeu les identifiants, les modes de rendu et les compteurs. En jeu, F1 l’ouvre et le referme.',
    'dbg.actif': 'Activer',

    'heb.percageTitre': 'Être joignable sans ouvrir de port',
    'heb.percage': 'Percer',
    'heb.percageDetail':
      'Ton serveur s’annonce à un point de rendez-vous public, et le chemin s’ouvre des deux côtés. Ça marche sur la plupart des box — pas sur toutes : certaines changent de port à chaque envoi, et là il faut une redirection.',
    'heb.billetTitre': 'Ton billet',
    'heb.billetAttente': 'Démarre le serveur : le billet arrive en quelques secondes.',
    'heb.copierLien': 'Copier le lien',

    'err.adminSansCle': 'Aucune clé d’administration pour ce serveur.',
    'err.adminRefuse': 'Clé refusée par ce serveur.',
    'err.adminHttp': 'Le serveur a répondu {code}.',
    'err.adminInjoignable': 'Serveur injoignable ({raison}).',
    'err.commandeVide': 'Écris une commande.',
    'nav.heberger': 'Héberger',

    'serv.parNom': 'Tu peux aussi écrire simplement le NOM d’un serveur public — « Voyage Public 2 » suffit, le lanceur le trouve dans l’annuaire.',
    'serv.cherche': 'Recherche de « {nom} » dans l’annuaire…',
    'serv.billetCherche': 'Billet {billet} — recherche de l’hôte au point de rendez-vous…',
    'serv.billetCible': 'billet {billet}',
    'serv.billetEnCours': 'Les deux côtés percent. Ça prend une seconde ou deux.',
    'serv.introuvableNom': 'Aucun serveur public ne porte ce nom. Vérifie l’orthographe, ou demande son adresse à celui qui héberge.',

    'heb.titre': 'Héberger depuis chez toi',
    'heb.arrete': 'Aucun serveur en marche',
    'heb.enMarche': '{nom} — port {port}',
    'heb.avant': 'Le lanceur démarre un serveur sur ta machine, avec TA partie dedans. Tes amis s’y branchent avec ton adresse.',
    'heb.pendant': 'Tes amis se branchent avec l’adresse ci-dessous. Laisse le lanceur ouvert.',
    'heb.demarrer': 'Démarrer',
    'heb.arreter': 'Arrêter',
    'heb.nomPlaceholder': 'Le nom que verront tes amis',
    'heb.mdpPlaceholder': 'Mot de passe (vide = ouvert)',
    'heb.places': 'Places et port',
    'heb.placesDetail': 'Jusqu’à 16 joueurs. Le port du jeu ; celui des infos est le suivant.',
    'heb.partageTitre': 'Partager ta partie',
    'heb.partage': 'Partager',
    'heb.partageDetail':
      'Ta sauvegarde est copiée dans le serveur au démarrage. Tes amis appuient sur F7 en jeu et reçoivent ton monde — ton radeau, tes machines, tes constructions.',
    'heb.publicTitre': 'Apparaître dans l’annuaire',
    'heb.public': 'Rendre public',
    'heb.publicDetail':
      'Ton serveur apparaît dans la liste du lanceur de tout le monde. Ça publie l’adresse de ta machine : à n’allumer que si tu le veux vraiment.',
    'heb.pareFeu':
      'Au premier démarrage, Windows demande d’autoriser le réseau : accepte, sinon personne ne pourra entrer. Pour des amis hors de ta maison, il faut aussi ouvrir le port sur ta box.',
    'heb.joueursTitre': 'Sur ton serveur',
    'heb.joueurs': 'Qui est connecté',
    'heb.personne': 'Personne pour l’instant.',
    'heb.ciblePlaceholder': 'Pseudo',
    'heb.dureePlaceholder': '2h, 7j…',
    'heb.expulser': 'Expulser',
    'heb.bannir': 'Bannir',
    'heb.commandePlaceholder': 'Une commande du serveur, par exemple /joueurs',
    'heb.envoyer': 'Envoyer',
    'heb.demarrage': 'démarrage de « {nom} » sur le port {port}…',
    'heb.enLigne': 'en ligne sur le port {port}',
    'heb.mondePose': 'ta partie est dans le serveur ({fichiers} fichier(s), {ko} ko)',
    'heb.arreteCode': 'serveur arrêté (code {code})',
    'heb.pasDemarre': 'le serveur n’a pas démarré : {raison}',
    'heb.force': 'le serveur ne répondait plus : arrêt forcé',
    'heb.annuaireOk': 'visible dans l’annuaire public.',
    'heb.annuaireNon': 'pas encore visible de l’extérieur : {raison}. Il faut ouvrir le port {port} sur ta box.',
    'heb.percageEteint': 'perçage éteint : tes amis doivent pouvoir joindre le port {port}.',
    'heb.percageAttente': 'perçage : en attente du point de rendez-vous…',
    'heb.percageBillet': 'billet {billet} — tes amis saisissent ça au lieu d’une adresse.',
    'heb.percageSymetrique':
      'ta box change de port à chaque envoi (NAT symétrique) : le perçage ne peut pas marcher, il faut ouvrir le port {port}.',
    'heb.percageRefus': 'perçage impossible : {raison}',
    'heb.annuaireEteint': 'annuaire éteint — ton serveur n’est visible que par ceux à qui tu donnes l’adresse.',
    'heb.expulse': '{nom} a été expulsé.',
    'heb.banni': '{nom} a été banni.',
    'heb.donneCible': 'Écris le pseudo de la personne.',

    'err.serveurIntrouvable': 'Le serveur embarqué est introuvable dans le lanceur.',
    'err.serveurPasDemarre': 'Le serveur n’a pas démarré. Regarde le journal en bas.',
    'err.aucuneSauvegarde': 'Aucune sauvegarde à partager : lance le jeu et crée une partie d’abord.',
    'err.donnees': 'Dossier de données introuvable.',
    'err.sauvegardes': 'Dossier de sauvegardes introuvable. Lance le jeu une fois, puis réessaie.',
    'chat.global': 'Tout le monde',
    'chat.local': 'Autour de moi',
    'chat.equipe': 'Mon équipe',

    'cmd.placeholder': 'Une commande du serveur, par exemple /joueurs',
    'cmd.envoyer': 'Envoyer',
    'cmd.aide': 'Tape /aide pour la liste. Le serveur décide de ce que tu as le droit de faire.',

    'partie.titre': 'La partie en cours',
    'partie.joueurs': 'Qui est là',
    'partie.vide': 'Branche-toi à un serveur pour voir la partie.',
    'partie.equipes': 'Équipes',
    'partie.aucuneEquipe': 'Aucune équipe. En jeu : /equipe creer Phare',
    'partie.activites': 'Objectifs',
    'partie.aucuneActivite': 'Aucun objectif. En jeu : /activite creer Réparer le générateur | Trouver la pièce',
    'partie.mesures': '{joueurs} joueur(s) · {entrant} ko/s entrants · tick {tick} ms · {memoire} Mo',
    'partie.mesuresInconnues': 'Mesures indisponibles sur ce serveur.',
    'partie.pret': 'prêt',

    'coffre.titre': 'Coffre commun',
    'coffre.contenu': 'Ce qu’il contient',
    'coffre.vide': 'Vide pour l’instant. En jeu, F10 te le montre.',
    'coffre.objet': 'Nom de l’objet, tel que le jeu l’appelle',
    'coffre.deposer': 'Déposer',
    'coffre.retirer': 'Retirer',
    'coffre.aide':
      'Le serveur tient le coffre et retire l’objet avant de l’annoncer : rien ne se duplique. C’est le seul échange d’objets possible entre deux parties séparées.',
    'coffre.envoye': 'Demande envoyée au serveur.',

    'ident.titre': 'Ton identité',
    'ident.detail':
      'Une clé fabriquée sur cette machine. C’est cette empreinte qu’un hôte inscrit pour te donner un rôle. La partie privée ne sort jamais d’ici.',
    'ident.copier': 'Copier',
    'ident.copie': 'Empreinte copiée.',
    'ident.refaireTitre': 'Recommencer à zéro',
    'ident.refaireDetail':
      'Une nouvelle identité te fait repartir inconnu partout : rôles, profil et heures de jeu restent attachés à l’ancienne. L’ancienne clé est mise de côté, pas effacée.',
    'ident.refaire': 'Nouvelle identité',
    'ident.confirme': 'Tu repars inconnu sur tous les serveurs. Continuer ?',
    'ident.refait': 'Nouvelle identité : {empreinte}',

    'nav.installation': 'Installation',
    'nav.serveurs': 'Serveurs',
    'nav.diagnostic': 'Diagnostic',
    'nav.reglages': 'Réglages',

    'inst.titreJeu': 'Le jeu',
    'inst.jeu': 'The Last Caretaker',
    'inst.recherche': 'Recherche en cours…',
    'inst.introuvable': 'Introuvable. Clique sur « Choisir » et indique le dossier du jeu.',
    'inst.choisir': 'Choisir',
    'inst.aInstaller': 'Ce qu’il faut installer',
    'inst.ue4ssDetail': 'Le socle qui fait tourner les mods. Le lanceur le livre avec lui, rien à télécharger.',
    'inst.telecharger': 'Installer UE4SS',
    'inst.parcourir': 'J’en ai déjà un',
    'inst.mods': 'Mods Voyage',
    'inst.modsDetail': 'VoyageLien envoie ta position au serveur. VoyageSonde relève de quoi diagnostiquer.',
    'inst.tout': 'Tout installer',
    'inst.toutDetail':
      'Un clic : télécharge UE4SS, l’installe dans le jeu avec nos mods, et vérifie que tout est en place.',
    'inst.toutBouton': 'Tout installer',
    'inst.retirer': 'Retirer',
    'inst.reversible': 'Un UE4SS déjà en place n’est pas touché, et tes autres mods non plus. Réversible.',
    'inst.trouve': 'trouvé',
    'inst.absent': 'absent',
    'inst.installe': 'installé',
    'inst.aFaire': 'à installer',
    'inst.dossierEnregistre': 'Dossier du jeu enregistré.',
    'inst.ue4ssEnregistre': 'Dossier UE4SS enregistré.',
    'inst.termine': 'Installation terminée.',
    'inst.retire': 'Retiré du jeu.',
    'inst.indiqueJeu': 'Indique d’abord où est le jeu.',

    'serv.pseudo': 'Ton pseudo',
    'serv.pseudoPlaceholder': 'Ton nom dans la partie',
    'serv.enregistrer': 'Enregistrer',
    'serv.pseudoOk': 'Tu t’appelleras « {nom} » en partie.',
    'serv.ajouter': 'Ajouter un serveur',
    'serv.adressePlaceholder': 'adresse:port',
    'serv.boutonAjouter': 'Ajouter',
    'serv.actualiser': 'Actualiser',
    'serv.ajoute': 'Serveur ajouté.',
    'serv.tiens': 'Tes serveurs',
    'serv.aucun': 'Aucun serveur enregistré. Ajoute son adresse au-dessus.',
    'serv.interrogation': 'Interrogation…',
    'serv.enLigne': 'en ligne',
    'serv.horsLigne': 'hors ligne',
    'serv.muet': 'ne répond pas',
    'serv.joueurs': 'joueurs',
    'serv.protege': 'mot de passe',
    'serv.connecter': 'Connecter',
    'serv.lancer': 'Lancer le jeu',
    'serv.retirer': 'Retirer',
    'serv.motDePasse': 'Mot de passe de « {nom} » :',

    'lien.titre': 'Le lien',
    'lien.pas': 'Pas connecté',
    'lien.vers': 'Connecté à {adresse}',
    'lien.deconnecter': 'Déconnecter',
    'chat.titre': 'Parler aux autres',
    'chat.sousTitre': 'Le chat s’écrit ici',
    'chat.aide': 'Le jeu ne peut pas capturer de texte : écris ton message ici, il s’affichera à l’écran de tout le monde.',
    'chat.placeholder': 'Ton message…',
    'chat.envoyer': 'Envoyer',
    'lien.avant':
      'Connecte-toi d’abord, puis lance le jeu et charge une partie : ta position part toute seule.',
    'lien.pendant':
      'Lance le jeu et charge une partie : ta position part toute seule. Au menu, rien n’est envoyé.',
    'lien.demarre': 'Pont démarré. Lance le jeu et charge une partie.',
    'lien.arrete': 'Pont arrêté.',
    'lien.jeuDemarre': 'Le jeu démarre.',

    'diag.titre': 'Est-ce qu’UE4SS se charge ?',
    'diag.analyser': 'Analyser',
    'diag.analyserTitre': 'Analyser l’installation',
    'diag.analyserDetail': 'Lance le jeu au moins une fois, puis reviens analyser.',
    'diag.cliqueAnalyser': 'Clique sur « Analyser ».',
    'diag.accroche': 'Point d’accroche',
    'diag.accrocheDetail':
      'Un jeu ne charge que les DLL qu’il importe. Si UE4SS reste muet, essaie-en un autre.',
    'diag.changer': 'Changer',
    'diag.enPlace': 'En place : {liste}',
    'diag.aucuneAccroche': 'Aucun point d’accroche installé.',
    'diag.charge': 'UE4SS se charge',
    'diag.chargeOui': 'UE4SS.log écrit le {date}',
    'diag.chargeNon': 'Aucun UE4SS.log. Le jeu ne charge pas la DLL : change de point d’accroche ci-dessous.',
    'diag.modVu': 'Nos mods sont vus par UE4SS',
    'diag.modVuOui': 'Ils apparaissent dans le journal.',
    'diag.modVuNon': 'Ils n’apparaissent pas dans le journal d’UE4SS.',
    'diag.rapport': 'Rapport de la sonde',
    'diag.rapportOui': 'VoyageSonde.txt trouvé.',
    'diag.rapportNon': 'Pas encore écrit : lance le jeu et laisse-le arriver au menu.',
    'diag.oui': 'oui',
    'diag.non': 'non',
    'diag.accrocheChangee': 'Point d’accroche : {nom}. Relance le jeu, puis analyse de nouveau.',
    'diag.console':
      'La console du jeu n’est pas sur F8 : c’est la touche à gauche du 1, ² / ~, ou F10.',

    'regl.langue': 'Langue',
    'regl.langueDetail': 'Elle s’applique tout de suite et sera retenue.',
    'regl.aPropos': 'À propos',
    'regl.version': 'Version {v}',
    'regl.aProposDetail':
      'Lanceur indépendant pour la coopération sur The Last Caretaker. Il n’embarque aucun fichier du jeu et ne modifie rien hors du dossier du jeu.',
    'regl.dossiers': 'Dossiers',
    'regl.ouvrirJeu': 'Ouvrir le dossier du jeu',

    'tele.enCours': 'Téléchargement d’UE4SS… {pourcent} %',
    'tele.extraction': 'Extraction…',
    'tele.fini': 'UE4SS {version} installé.',
    'jrn.jeuTrouve': 'Jeu trouvé : {dossier}',
    'jrn.ue4ssTelecharge': 'UE4SS {version} téléchargé.',
    'jrn.ue4ssDeja': 'UE4SS déjà en place : on ajoute seulement nos mods.',
    'jrn.egare': 'Retiré d’un dossier inutile : {chemin}',
    'jrn.ue4ssInstalle': 'UE4SS installé.',
    'jrn.ue4ssGarde': 'UE4SS laissé en place : il n’a pas été installé par nous.',
    'err.archiveAbsente': 'L’archive UE4SS livrée avec le lanceur est introuvable.',
    'err.archiveAlteree': 'L’archive UE4SS livrée ne correspond pas à son empreinte.',
    'err.extraction': 'Impossible d’extraire l’archive UE4SS.',
    'err.ue4ssManquant': 'UE4SS est absent et aucune source n’a été fournie.',
    'jrn.console': 'Console UE4SS activée (elle prouve qu’il se charge).',
    'jrn.modPose': 'Mod « {nom} » posé.',
    'jrn.modActive': '« {nom} » activé dans mods.txt.',
    'jrn.retire': '{quoi} retiré.',

    'lien.demarrage': 'démarrage du pont vers {adresse}…',
    'lien.pasDemarre': 'le pont n’a pas pu démarrer : {raison}',
    'lien.fini': 'pont arrêté.',
    'lien.finiCode': 'pont arrêté (code {code}).',

    'err.binaires': 'Binaries/Win64 est introuvable dans le jeu.',
    'err.pasBinaires': 'Ce dossier ne contient pas Binaries/Win64. Choisis le dossier du jeu lui-même.',
    'err.pasUne4ss': 'Ce dossier ne ressemble pas à une release UE4SS (dwmapi.dll et ue4ss/ attendus).',
    'err.pasDwmapi': 'dwmapi.dll est introuvable ici. Choisis le dossier extrait de la release UE4SS.',
    'err.indiqueUe4ss': 'Indique d’abord où tu as extrait UE4SS, ou clique sur « Télécharger ».',
    'err.jeuIntrouvable': 'Le jeu est introuvable. Indique son dossier d’abord.',
    'err.installIncomplete': 'L’installation s’est terminée mais quelque chose manque.',
    'err.accrocheInconnue': 'Point d’accroche inconnu.',
    'err.ue4ssPasInstalle': 'UE4SS n’est pas installé : installe-le d’abord.',
    'err.pontIntrouvable': 'Le pont est introuvable dans le lanceur.',
    'err.dossierInconnu': 'Dossier inconnu.',
    'err.dossierDisparu': 'Ce dossier n’existe plus.',
    'err.pseudoVide': 'Choisis un pseudo.',
    'err.pasDeRapport': 'Pas encore de rapport. Lance le jeu et laisse-le arriver au menu.',
    'err.archivePasUe4ss': 'L’archive téléchargée ne ressemble pas à UE4SS.',
    'nav.monde': 'Monde',
    'monde.tienne': 'Ta partie',
    'monde.dossier': 'Dossier des sauvegardes',
    'monde.aucunDossier': 'Introuvable. Le jeu range ses parties dans ton profil, pas dans son dossier.',
    'monde.fichiers': '{n} fichier(s)',
    'monde.publierTitre': 'Publier ta partie sur le serveur',
    'monde.publierDetail': 'Les autres pourront l’installer et jouer dans TON monde. Il faut le mot de passe du monde.',
    'monde.publier': 'Publier',
    'monde.mettreDeCote': 'Copier de côté',
    'monde.nomPlaceholder': 'Nom du monde (ex. Le Radeau)',
    'monde.etiquettePlaceholder': 'Nom de la partie dans le jeu',
    'monde.motDePasseMonde': 'Mot de passe du monde (celui de l’hôte, pas celui du serveur) :',
    'monde.duServeur': 'Le monde du serveur',
    'monde.aucunDistant': 'Aucun monde publié',
    'monde.choisirServeur': 'Choisis un serveur, puis « Aperçu ».',
    'monde.publieLe': '« {nom} » par {par}, {fichiers} fichier(s), {ko} ko — {date}',
    'monde.apercu': 'Aperçu',
    'monde.installer': 'Installer ce monde',
    'monde.ceQuiChange': 'Ce que l’installation change',
    'monde.avertissement': 'Installer un monde REMPLACE tes parties du même nom. Une copie de ta partie est faite avant, automatiquement.',
    'monde.resume': '{ajoutes} ajouté(s) · {remplaces} remplacé(s) · {locaux} gardé(s) chez toi',
    'monde.refusees': '{n} fichier(s) refusé(s) par sécurité : {liste}',
    'monde.coffre': 'Tes copies de sauvegarde',
    'monde.aucuneCopie': 'Aucune copie pour l’instant. Il s’en fait une à chaque installation.',
    'monde.restaurer': 'Restaurer',
    'monde.publieOk': 'Monde publié : « {nom} ».',
    'monde.installeOk': '{n} fichier(s) installé(s). Charge la partie « {etiquette} » dans le jeu.',
    'monde.restaureOk': '{n} fichier(s) restauré(s).',
    'monde.copieOk': 'Copie faite : {chemin}',
    'monde.aucunServeur': 'Ajoute d’abord un serveur dans l’onglet Serveurs.',
    'erreur.inconnue': 'Erreur inconnue.',
  },

  en: {
    'appli.sousTitre': 'Co-op for The Last Caretaker — Symbiose Héritage',
    'appli.pied': 'Independent project — no game files are distributed',
    'serv.public': 'public directory',
    'serv.ping': '{ms} ms',
    'serv.garder': 'Keep',
    'cre.titre': 'Creatures',
    'cre.sousTitre': 'What you see of sharks, angels and swarms',
    'cre.detail':
      'The game spawns its creatures for each player separately: nothing links your shark to your friend’s. The mirror hides yours and shows the host’s — the only way to see the same one.',
    'cre.miroir': 'The host’s (mirror)',
    'cre.annonce': 'Mine, and tell me about theirs',
    'cre.rien': 'Mine only',
    'cre.note': 'In game, F2 switches without coming here — handy if something goes wrong mid-session.',
    'serv.lien': 'Link',
    'serv.lienCopie': 'Invite link copied — paste it to your friends.',
    'serv.administrer': 'Administer',
    'serv.aucunFiltre': 'No server passes your filters.',
    'adm.demandeCle': 'Admin key for “{nom}”. This is NOT the server password: it is the ADMIN_CLE set in its settings.',
    'adm.invite': '{nom}\n\n{joueurs}\n\nA command to run?',
    'inv.titre': 'Someone is inviting you',
    'inv.adresse': 'Server {adresse}{protege}',
    'inv.billet': 'Ticket {billet}{protege}',
    'inv.protege': ' — a password will be asked',
    'inv.rejoindre': 'Join',
    'inv.ignorer': 'Ignore',

    'filtre.titre': 'Filter the list',
    'filtre.detail': 'Applied to what you already see, without asking the network again.',
    'filtre.enLigne': 'Online',
    'filtre.libres': 'Free slots',
    'filtre.ouverts': 'No password',

    'maj.titre': 'Updates',
    'maj.inconnue': 'Launcher version unknown',
    'maj.aJour': 'Launcher {v} — up to date',
    'maj.disponible': 'Launcher {v} — {nouvelle} is out',
    'maj.echec': 'Could not check ({raison})',
    'maj.lanceurDetail': 'We look, we download nothing on our own. A launcher that is too old gets refused by servers.',
    'maj.verifier': 'Check',
    'maj.telecharger': 'Open the page',
    'maj.installer': 'Download and install',
    'maj.enCours': 'Downloading… {pourcent}%',
    'maj.verifiee': 'Version {v} downloaded, checksum verified.',
    'maj.fermeture': 'The launcher will close so the installer can work.',
    'err.archiveDouteuse': 'Archive refused: it contains “{nom}”, which is not a save file. Nothing was extracted.',
    'err.majRien': 'There is nothing newer to install.',
    'err.majPasPret': 'Nothing was downloaded: run the check again.',
    'err.majNom': 'The announced file name is refused.',
    'err.majSansEmpreinte': 'No checksum published: we refuse to install a file we cannot verify.',
    'err.majEmpreinte': 'The file received does not match the published checksum. Nothing was installed.',
    'err.majServeurEnMarche': 'Stop your server first: the installer would close your players’ game.',
    'maj.jeuTitre': 'The game',
    'maj.jeuInconnu': 'Game version unknown — point to its folder in the Install tab.',
    'maj.jeuConnu': 'Steam build {build}, unchanged since last time.',
    'maj.jeuChange': 'The game was updated ({avant} → {build}). The mod has not been checked against this version yet: if something is off, tell us.',
    'maj.jeuPremier': 'Steam build {build} — remembered, so we can spot the next update.',

    'sout.titre': 'Support pack',
    'sout.sousTitre': 'Everything needed to understand a problem',
    'sout.detail': 'Versions, logs, diagnostics and fingerprints, in a text file on your desktop.',
    'sout.fabriquer': 'Create',
    'sout.expurge': 'Lines that might hold a password, a key or a token are removed — and the removal is written down, so nothing goes missing silently.',
    'sout.fait': 'Pack written to your desktop: {nom}',

    'pl.titre': 'Names above heads',
    'pl.sousTitre': 'What you show on other players',
    'pl.detail': 'These settings never leave your machine: they only decide what YOU see.',
    'pl.noms': 'Name',
    'pl.distance': 'Distance',
    'pl.ping': 'Ping',
    'pl.vie': 'Health',
    'pl.porteeTitre': 'Up to what distance',
    'pl.porteeDetail': 'In metres. Beyond that the plate disappears rather than becoming unreadable.',

    'dbg.titre': 'Debug mode',
    'dbg.detail': 'Shows identifiers, render modes and counters in game. In game, F1 opens and closes it.',
    'dbg.actif': 'Enable',

    'heb.percageTitre': 'Be reachable without opening a port',
    'heb.percage': 'Punch through',
    'heb.percageDetail':
      'Your server announces itself to a public rendezvous, and the path opens on both sides. It works on most home routers — not all: some change port on every send, and those need a forwarded port.',
    'heb.billetTitre': 'Your ticket',
    'heb.billetAttente': 'Start the server: the ticket arrives within seconds.',
    'heb.copierLien': 'Copy the link',

    'err.adminSansCle': 'No admin key for this server.',
    'err.adminRefuse': 'Key refused by this server.',
    'err.adminHttp': 'The server answered {code}.',
    'err.adminInjoignable': 'Server unreachable ({raison}).',
    'err.commandeVide': 'Type a command.',
    'nav.heberger': 'Host',

    'serv.parNom': 'You can also just type a public server’s NAME — “Voyage Public 2” is enough, the launcher finds it in the directory.',
    'serv.cherche': 'Looking for “{nom}” in the directory…',
    'serv.billetCherche': 'Ticket {billet} — looking for the host at the rendezvous…',
    'serv.billetCible': 'ticket {billet}',
    'serv.billetEnCours': 'Both sides are punching through. Give it a second or two.',
    'serv.introuvableNom': 'No public server goes by that name. Check the spelling, or ask the host for the address.',

    'heb.titre': 'Host from your own machine',
    'heb.arrete': 'No server running',
    'heb.enMarche': '{nom} — port {port}',
    'heb.avant': 'The launcher starts a server on your machine, with YOUR save inside. Your friends connect with your address.',
    'heb.pendant': 'Your friends connect with the address below. Leave the launcher open.',
    'heb.demarrer': 'Start',
    'heb.arreter': 'Stop',
    'heb.nomPlaceholder': 'The name your friends will see',
    'heb.mdpPlaceholder': 'Password (empty = open)',
    'heb.places': 'Slots and port',
    'heb.placesDetail': 'Up to 16 players. The game port; the info port is the next one.',
    'heb.partageTitre': 'Share your save',
    'heb.partage': 'Share',
    'heb.partageDetail':
      'Your save is copied into the server at startup. Your friends press F7 in game and get your world — your raft, your machines, your buildings.',
    'heb.publicTitre': 'Appear in the directory',
    'heb.public': 'Make public',
    'heb.publicDetail':
      'Your server shows up in everyone’s launcher list. That publishes your machine’s address: only turn it on if you really want to.',
    'heb.pareFeu':
      'On the first start Windows asks to allow network access: accept, or nobody can get in. For friends outside your home, you also need to open the port on your router.',
    'heb.joueursTitre': 'On your server',
    'heb.joueurs': 'Who is connected',
    'heb.personne': 'Nobody yet.',
    'heb.ciblePlaceholder': 'Nickname',
    'heb.dureePlaceholder': '2h, 7j…',
    'heb.expulser': 'Kick',
    'heb.bannir': 'Ban',
    'heb.commandePlaceholder': 'A server command, for example /joueurs',
    'heb.envoyer': 'Send',
    'heb.demarrage': 'starting “{nom}” on port {port}…',
    'heb.enLigne': 'online on port {port}',
    'heb.mondePose': 'your save is in the server ({fichiers} file(s), {ko} kB)',
    'heb.arreteCode': 'server stopped (code {code})',
    'heb.pasDemarre': 'the server did not start: {raison}',
    'heb.force': 'the server stopped responding: forced shutdown',
    'heb.annuaireOk': 'visible in the public directory.',
    'heb.annuaireNon': 'not reachable from outside yet: {raison}. You need to open port {port} on your router.',
    'heb.percageEteint': 'hole punching off: your friends need to be able to reach port {port}.',
    'heb.percageAttente': 'hole punching: waiting for the rendezvous point…',
    'heb.percageBillet': 'ticket {billet} — your friends type this instead of an address.',
    'heb.percageSymetrique':
      'your router changes port on every packet (symmetric NAT): hole punching cannot work, you need to open port {port}.',
    'heb.percageRefus': 'hole punching impossible: {raison}',
    'heb.annuaireEteint': 'directory off — your server is only visible to those you give the address to.',
    'heb.expulse': '{nom} was kicked.',
    'heb.banni': '{nom} was banned.',
    'heb.donneCible': 'Type the person’s nickname.',

    'err.serveurIntrouvable': 'The bundled server is missing from the launcher.',
    'err.serveurPasDemarre': 'The server did not start. Check the log below.',
    'err.aucuneSauvegarde': 'No save to share: start the game and create one first.',
    'err.donnees': 'Data folder not found.',
    'err.sauvegardes': 'Save folder not found. Run the game once, then try again.',
    'chat.global': 'Everyone',
    'chat.local': 'Around me',
    'chat.equipe': 'My team',

    'cmd.placeholder': 'A server command, for example /joueurs',
    'cmd.envoyer': 'Send',
    'cmd.aide': 'Type /aide for the list. The server decides what you are allowed to do.',

    'partie.titre': 'The session',
    'partie.joueurs': 'Who is here',
    'partie.vide': 'Connect to a server to see the session.',
    'partie.equipes': 'Teams',
    'partie.aucuneEquipe': 'No teams. In game: /equipe creer Lighthouse',
    'partie.activites': 'Objectives',
    'partie.aucuneActivite': 'No objectives. In game: /activite creer Repair the generator | Find the part',
    'partie.mesures': '{joueurs} player(s) · {entrant} kB/s in · tick {tick} ms · {memoire} MB',
    'partie.mesuresInconnues': 'Metrics unavailable on this server.',
    'partie.pret': 'ready',

    'coffre.titre': 'Shared stash',
    'coffre.contenu': 'What it holds',
    'coffre.vide': 'Empty for now. In game, F10 shows it.',
    'coffre.objet': 'Item name, as the game calls it',
    'coffre.deposer': 'Deposit',
    'coffre.retirer': 'Withdraw',
    'coffre.aide':
      'The server holds the stash and removes the item before announcing it, so nothing duplicates. It is the only way to move items between two separate saves.',
    'coffre.envoye': 'Request sent to the server.',

    'ident.titre': 'Your identity',
    'ident.detail':
      'A key made on this machine. This fingerprint is what a host writes down to give you a role. The private half never leaves here.',
    'ident.copier': 'Copy',
    'ident.copie': 'Fingerprint copied.',
    'ident.refaireTitre': 'Start over',
    'ident.refaireDetail':
      'A new identity makes you a stranger everywhere: roles, profile and playtime stay with the old one. The old key is set aside, not deleted.',
    'ident.refaire': 'New identity',
    'ident.confirme': 'You will be a stranger on every server. Continue?',
    'ident.refait': 'New identity: {empreinte}',

    'nav.installation': 'Setup',
    'nav.serveurs': 'Servers',
    'nav.diagnostic': 'Diagnostics',
    'nav.reglages': 'Settings',

    'inst.titreJeu': 'The game',
    'inst.jeu': 'The Last Caretaker',
    'inst.recherche': 'Looking for it…',
    'inst.introuvable': 'Not found. Click “Choose” and point to the game folder.',
    'inst.choisir': 'Choose',
    'inst.aInstaller': 'What needs installing',
    'inst.ue4ssDetail': 'The layer that runs the mods. The launcher ships it, nothing to download.',
    'inst.telecharger': 'Install UE4SS',
    'inst.parcourir': 'I already have it',
    'inst.mods': 'Voyage mods',
    'inst.modsDetail': 'VoyageLien sends your position to the server. VoyageSonde gathers diagnostics.',
    'inst.tout': 'Install everything',
    'inst.toutDetail':
      'One click: downloads UE4SS, installs it into the game along with our mods, and checks the result.',
    'inst.toutBouton': 'Install everything',
    'inst.retirer': 'Remove',
    'inst.reversible': 'An existing UE4SS is left alone, and so are your other mods. Reversible.',
    'inst.trouve': 'found',
    'inst.absent': 'missing',
    'inst.installe': 'installed',
    'inst.aFaire': 'to install',
    'inst.dossierEnregistre': 'Game folder saved.',
    'inst.ue4ssEnregistre': 'UE4SS folder saved.',
    'inst.termine': 'Install finished.',
    'inst.retire': 'Removed from the game.',
    'inst.indiqueJeu': 'Point to the game first.',

    'serv.pseudo': 'Your name',
    'serv.pseudoPlaceholder': 'Your name in game',
    'serv.enregistrer': 'Save',
    'serv.pseudoOk': 'You’ll be “{nom}” in game.',
    'serv.ajouter': 'Add a server',
    'serv.adressePlaceholder': 'address:port',
    'serv.boutonAjouter': 'Add',
    'serv.actualiser': 'Refresh',
    'serv.ajoute': 'Server added.',
    'serv.tiens': 'Your servers',
    'serv.aucun': 'No server saved yet. Add its address above.',
    'serv.interrogation': 'Asking…',
    'serv.enLigne': 'online',
    'serv.horsLigne': 'offline',
    'serv.muet': 'no answer',
    'serv.joueurs': 'players',
    'serv.protege': 'password',
    'serv.connecter': 'Connect',
    'serv.lancer': 'Start the game',
    'serv.retirer': 'Remove',
    'serv.motDePasse': 'Password for “{nom}”:',

    'lien.titre': 'The link',
    'lien.pas': 'Not connected',
    'lien.vers': 'Connected to {adresse}',
    'lien.deconnecter': 'Disconnect',
    'chat.titre': 'Talk to the others',
    'chat.sousTitre': 'Chat is typed here',
    'chat.aide': 'The game cannot capture text: type your message here and it will appear on everyone’s screen.',
    'chat.placeholder': 'Your message…',
    'chat.envoyer': 'Send',
    'lien.avant': 'Connect first, then start the game and load a save: your position goes on its own.',
    'lien.pendant':
      'Start the game and load a save: your position goes on its own. Nothing is sent from the menu.',
    'lien.demarre': 'Bridge started. Start the game and load a save.',
    'lien.arrete': 'Bridge stopped.',
    'lien.jeuDemarre': 'The game is starting.',

    'diag.titre': 'Is UE4SS loading?',
    'diag.analyser': 'Analyse',
    'diag.analyserTitre': 'Analyse the install',
    'diag.analyserDetail': 'Run the game at least once, then come back and analyse.',
    'diag.cliqueAnalyser': 'Click “Analyse”.',
    'diag.accroche': 'Hook',
    'diag.accrocheDetail': 'A game only loads the DLLs it imports. If UE4SS stays silent, try another.',
    'diag.changer': 'Change',
    'diag.enPlace': 'In place: {liste}',
    'diag.aucuneAccroche': 'No hook installed.',
    'diag.charge': 'UE4SS loads',
    'diag.chargeOui': 'UE4SS.log written on {date}',
    'diag.chargeNon': 'No UE4SS.log. The game isn’t loading the DLL: change the hook below.',
    'diag.modVu': 'UE4SS sees our mods',
    'diag.modVuOui': 'They show up in the log.',
    'diag.modVuNon': 'They don’t show up in the UE4SS log.',
    'diag.rapport': 'Probe report',
    'diag.rapportOui': 'VoyageSonde.txt found.',
    'diag.rapportNon': 'Not written yet: start the game and let it reach the menu.',
    'diag.oui': 'yes',
    'diag.non': 'no',
    'diag.accrocheChangee': 'Hook: {nom}. Restart the game, then analyse again.',
    'diag.console': 'The game console is not on F8: it’s the key left of 1, ² / ~, or F10.',

    'regl.langue': 'Language',
    'regl.langueDetail': 'Applied right away and remembered.',
    'regl.aPropos': 'About',
    'regl.version': 'Version {v}',
    'regl.aProposDetail':
      'Independent launcher for co-op on The Last Caretaker. It ships no game files and touches nothing outside the game folder.',
    'regl.dossiers': 'Folders',
    'regl.ouvrirJeu': 'Open the game folder',

    'tele.enCours': 'Downloading UE4SS… {pourcent}%',
    'tele.extraction': 'Extracting…',
    'tele.fini': 'UE4SS {version} installed.',
    'jrn.jeuTrouve': 'Game found: {dossier}',
    'jrn.ue4ssTelecharge': 'UE4SS {version} downloaded.',
    'jrn.ue4ssDeja': 'UE4SS already here: only our mods were added.',
    'jrn.egare': 'Removed from a useless folder: {chemin}',
    'jrn.ue4ssInstalle': 'UE4SS installed.',
    'jrn.ue4ssGarde': 'UE4SS left in place: we did not install it.',
    'err.archiveAbsente': 'The UE4SS archive shipped with the launcher is missing.',
    'err.archiveAlteree': 'The UE4SS archive shipped with the launcher does not match its checksum.',
    'err.extraction': 'The UE4SS archive could not be extracted.',
    'err.ue4ssManquant': 'UE4SS is missing and no source was provided.',
    'jrn.console': 'UE4SS console enabled (it proves UE4SS loads).',
    'jrn.modPose': 'Mod “{nom}” placed.',
    'jrn.modActive': '“{nom}” enabled in mods.txt.',
    'jrn.retire': '{quoi} removed.',

    'lien.demarrage': 'starting the bridge to {adresse}…',
    'lien.pasDemarre': 'the bridge could not start: {raison}',
    'lien.fini': 'bridge stopped.',
    'lien.finiCode': 'bridge stopped (code {code}).',

    'err.binaires': 'Binaries/Win64 cannot be found in the game.',
    'err.pasBinaires': 'This folder has no Binaries/Win64. Pick the game folder itself.',
    'err.pasUne4ss': 'This folder does not look like a UE4SS release (dwmapi.dll and ue4ss/ expected).',
    'err.pasDwmapi': 'dwmapi.dll is not here. Pick the folder you extracted the UE4SS release into.',
    'err.indiqueUe4ss': 'Point to your UE4SS folder first, or click “Download”.',
    'err.jeuIntrouvable': 'The game cannot be found. Point to its folder first.',
    'err.installIncomplete': 'The install finished but something is missing.',
    'err.accrocheInconnue': 'Unknown hook.',
    'err.ue4ssPasInstalle': 'UE4SS is not installed: install it first.',
    'err.pontIntrouvable': 'The bridge is missing from the launcher.',
    'err.dossierInconnu': 'Unknown folder.',
    'err.dossierDisparu': 'That folder is gone.',
    'err.pseudoVide': 'Pick a name.',
    'err.pasDeRapport': 'No report yet. Start the game and let it reach the menu.',
    'err.archivePasUe4ss': 'The downloaded archive does not look like UE4SS.',
    'nav.monde': 'World',
    'monde.tienne': 'Your save',
    'monde.dossier': 'SaveGames folder',
    'monde.aucunDossier': 'Not found. The game keeps saves in your profile, not in its own folder.',
    'monde.fichiers': '{n} file(s)',
    'monde.publierTitre': 'Publish your save to the server',
    'monde.publierDetail': 'Others can install it and play in YOUR world. The world password is required.',
    'monde.publier': 'Publish',
    'monde.mettreDeCote': 'Copy aside',
    'monde.nomPlaceholder': 'World name (e.g. The Raft)',
    'monde.etiquettePlaceholder': 'Save name inside the game',
    'monde.motDePasseMonde': 'World password (the host’s, not the server’s):',
    'monde.duServeur': 'The server’s world',
    'monde.aucunDistant': 'No world published',
    'monde.choisirServeur': 'Pick a server, then “Preview”.',
    'monde.publieLe': '“{nom}” by {par}, {fichiers} file(s), {ko} kB — {date}',
    'monde.apercu': 'Preview',
    'monde.installer': 'Install this world',
    'monde.ceQuiChange': 'What installing changes',
    'monde.avertissement': 'Installing a world REPLACES your saves of the same name. A copy of your save is made first, automatically.',
    'monde.resume': '{ajoutes} added · {remplaces} replaced · {locaux} kept, yours only',
    'monde.refusees': '{n} file(s) refused for safety: {liste}',
    'monde.coffre': 'Your backups',
    'monde.aucuneCopie': 'No backup yet. One is made on every install.',
    'monde.restaurer': 'Restore',
    'monde.publieOk': 'World published: “{nom}”.',
    'monde.installeOk': '{n} file(s) installed. Load the “{etiquette}” save in game.',
    'monde.restaureOk': '{n} file(s) restored.',
    'monde.copieOk': 'Copy made: {chemin}',
    'monde.aucunServeur': 'Add a server in the Servers tab first.',
    'erreur.inconnue': 'Unknown error.',
  },

  es: {
    'appli.sousTitre': 'Cooperativo para The Last Caretaker — Symbiose Héritage',
    'appli.pied': 'Proyecto independiente — no se distribuye ningún archivo del juego',
    'serv.public': 'directorio público',
    'serv.ping': '{ms} ms',
    'serv.garder': 'Guardar',
    'cre.titre': 'Las criaturas',
    'cre.sousTitre': 'Lo que ves de tiburones, ángeles y enjambres',
    'cre.detail':
      'El juego crea sus criaturas en cada máquina por separado: nada une tu tiburón al de tu amigo. El espejo oculta las tuyas y muestra las del anfitrión — la única forma de ver la misma.',
    'cre.miroir': 'Las del anfitrión (espejo)',
    'cre.annonce': 'Las mías, y que me avisen de las suyas',
    'cre.rien': 'Solo las mías',
    'cre.note': 'En el juego, F2 cambia sin pasar por aquí — útil si algo falla en plena partida.',
    'serv.lien': 'Enlace',
    'serv.lienCopie': 'Enlace de invitación copiado — pégaselo a tus amigos.',
    'serv.administrer': 'Administrar',
    'serv.aucunFiltre': 'Ningún servidor pasa tus filtros.',
    'adm.demandeCle': 'Clave de administración de «{nom}». NO es la contraseña del servidor: es la ADMIN_CLE puesta en sus ajustes.',
    'adm.invite': '{nom}\n\n{joueurs}\n\n¿Un comando que lanzar?',
    'inv.titre': 'Alguien te invita',
    'inv.adresse': 'Servidor {adresse}{protege}',
    'inv.billet': 'Billete {billet}{protege}',
    'inv.protege': ' — se pedirá una contraseña',
    'inv.rejoindre': 'Entrar',
    'inv.ignorer': 'Ignorar',

    'filtre.titre': 'Filtrar la lista',
    'filtre.detail': 'Se aplica a lo que ya ves, sin volver a preguntar a la red.',
    'filtre.enLigne': 'En línea',
    'filtre.libres': 'Plazas libres',
    'filtre.ouverts': 'Sin contraseña',

    'maj.titre': 'Actualizaciones',
    'maj.inconnue': 'Versión del lanzador desconocida',
    'maj.aJour': 'Lanzador {v} — al día',
    'maj.disponible': 'Lanzador {v} — ha salido la {nouvelle}',
    'maj.echec': 'No se pudo comprobar ({raison})',
    'maj.lanceurDetail': 'Miramos, no descargamos nada por nuestra cuenta. Un lanzador demasiado antiguo es rechazado por los servidores.',
    'maj.verifier': 'Comprobar',
    'maj.telecharger': 'Abrir la página',
    'maj.installer': 'Descargar e instalar',
    'maj.enCours': 'Descargando… {pourcent} %',
    'maj.verifiee': 'Versión {v} descargada, huella verificada.',
    'maj.fermeture': 'El lanzador se cerrará para dejar trabajar al instalador.',
    'err.archiveDouteuse': 'Archivo rechazado: contiene «{nom}», que no es una partida guardada. No se extrajo nada.',
    'err.majRien': 'No hay nada más reciente que instalar.',
    'err.majPasPret': 'No se descargó nada: vuelve a comprobar.',
    'err.majNom': 'El nombre de archivo anunciado se rechaza.',
    'err.majSansEmpreinte': 'Ninguna huella publicada: nos negamos a instalar un archivo que no podemos verificar.',
    'err.majEmpreinte': 'El archivo recibido no coincide con la huella publicada. No se instaló nada.',
    'err.majServeurEnMarche': 'Para primero tu servidor: el instalador cerraría la partida de tus jugadores.',
    'maj.jeuTitre': 'El juego',
    'maj.jeuInconnu': 'Versión del juego desconocida — indica su carpeta en la pestaña Instalación.',
    'maj.jeuConnu': 'Build de Steam {build}, sin cambios desde la última vez.',
    'maj.jeuChange': 'El juego se actualizó ({avant} → {build}). El mod aún no se ha comprobado con esta versión: si algo falla, dínoslo.',
    'maj.jeuPremier': 'Build de Steam {build} — lo recordamos para detectar las próximas actualizaciones.',

    'sout.titre': 'Paquete de soporte',
    'sout.sousTitre': 'Todo lo necesario para entender un problema',
    'sout.detail': 'Versiones, registros, diagnósticos y huellas, en un archivo de texto en tu escritorio.',
    'sout.fabriquer': 'Crear',
    'sout.expurge': 'Las líneas que pudieran contener una contraseña, una clave o un token se retiran — y la retirada queda escrita, para que nada falte en silencio.',
    'sout.fait': 'Paquete escrito en tu escritorio: {nom}',

    'pl.titre': 'Los nombres sobre las cabezas',
    'pl.sousTitre': 'Lo que muestras sobre los demás jugadores',
    'pl.detail': 'Estos ajustes no salen de tu máquina: solo deciden lo que TÚ ves.',
    'pl.noms': 'Nombre',
    'pl.distance': 'Distancia',
    'pl.ping': 'Ping',
    'pl.vie': 'Vida',
    'pl.porteeTitre': 'Hasta qué distancia',
    'pl.porteeDetail': 'En metros. Más allá, la placa desaparece en vez de volverse ilegible.',

    'dbg.titre': 'Modo depuración',
    'dbg.detail': 'Muestra en el juego identificadores, modos de render y contadores. En el juego, F1 lo abre y lo cierra.',
    'dbg.actif': 'Activar',

    'heb.percageTitre': 'Ser accesible sin abrir un puerto',
    'heb.percage': 'Perforar',
    'heb.percageDetail':
      'Tu servidor se anuncia a un punto de encuentro público, y el camino se abre por ambos lados. Funciona en la mayoría de routers domésticos — no en todos: algunos cambian de puerto en cada envío, y esos necesitan una redirección.',
    'heb.billetTitre': 'Tu billete',
    'heb.billetAttente': 'Arranca el servidor: el billete llega en unos segundos.',
    'heb.copierLien': 'Copiar el enlace',

    'err.adminSansCle': 'No hay clave de administración para este servidor.',
    'err.adminRefuse': 'Clave rechazada por este servidor.',
    'err.adminHttp': 'El servidor respondió {code}.',
    'err.adminInjoignable': 'Servidor inaccesible ({raison}).',
    'err.commandeVide': 'Escribe un comando.',
    'nav.heberger': 'Alojar',

    'serv.parNom': 'También puedes escribir solo el NOMBRE de un servidor público — «Voyage Public 2» basta, el lanzador lo busca en el directorio.',
    'serv.cherche': 'Buscando «{nom}» en el directorio…',
    'serv.billetCherche': 'Billete {billet} — buscando al anfitrión en el punto de encuentro…',
    'serv.billetCible': 'billete {billet}',
    'serv.billetEnCours': 'Ambos lados están perforando. Tarda un segundo o dos.',
    'serv.introuvableNom': 'Ningún servidor público se llama así. Revisa la ortografía, o pide la dirección a quien aloja.',

    'heb.titre': 'Alojar desde tu propia máquina',
    'heb.arrete': 'Ningún servidor en marcha',
    'heb.enMarche': '{nom} — puerto {port}',
    'heb.avant': 'El lanzador arranca un servidor en tu máquina, con TU partida dentro. Tus amigos se conectan con tu dirección.',
    'heb.pendant': 'Tus amigos se conectan con la dirección de abajo. Deja el lanzador abierto.',
    'heb.demarrer': 'Arrancar',
    'heb.arreter': 'Detener',
    'heb.nomPlaceholder': 'El nombre que verán tus amigos',
    'heb.mdpPlaceholder': 'Contraseña (vacío = abierto)',
    'heb.places': 'Plazas y puerto',
    'heb.placesDetail': 'Hasta 16 jugadores. El puerto del juego; el de la información es el siguiente.',
    'heb.partageTitre': 'Compartir tu partida',
    'heb.partage': 'Compartir',
    'heb.partageDetail':
      'Tu partida se copia en el servidor al arrancar. Tus amigos pulsan F7 en el juego y reciben tu mundo — tu balsa, tus máquinas, tus construcciones.',
    'heb.publicTitre': 'Aparecer en el directorio',
    'heb.public': 'Hacer público',
    'heb.publicDetail':
      'Tu servidor aparece en la lista del lanzador de todos. Eso publica la dirección de tu máquina: enciéndelo solo si de verdad lo quieres.',
    'heb.pareFeu':
      'En el primer arranque Windows pide permitir la red: acepta, o nadie podrá entrar. Para amigos fuera de tu casa, también hay que abrir el puerto en el router.',
    'heb.joueursTitre': 'En tu servidor',
    'heb.joueurs': 'Quién está conectado',
    'heb.personne': 'Nadie por ahora.',
    'heb.ciblePlaceholder': 'Apodo',
    'heb.dureePlaceholder': '2h, 7j…',
    'heb.expulser': 'Expulsar',
    'heb.bannir': 'Banear',
    'heb.commandePlaceholder': 'Un comando del servidor, por ejemplo /joueurs',
    'heb.envoyer': 'Enviar',
    'heb.demarrage': 'arrancando «{nom}» en el puerto {port}…',
    'heb.enLigne': 'en línea en el puerto {port}',
    'heb.mondePose': 'tu partida está en el servidor ({fichiers} archivo(s), {ko} kB)',
    'heb.arreteCode': 'servidor detenido (código {code})',
    'heb.pasDemarre': 'el servidor no arrancó: {raison}',
    'heb.force': 'el servidor dejó de responder: parada forzada',
    'heb.annuaireOk': 'visible en el directorio público.',
    'heb.annuaireNon': 'aún no accesible desde fuera: {raison}. Hay que abrir el puerto {port} en el router.',
    'heb.percageEteint': 'perforación apagada: tus amigos deben poder alcanzar el puerto {port}.',
    'heb.percageAttente': 'perforación: esperando al punto de encuentro…',
    'heb.percageBillet': 'billete {billet} — tus amigos escriben esto en vez de una dirección.',
    'heb.percageSymetrique':
      'tu router cambia de puerto en cada envío (NAT simétrico): la perforación no puede funcionar, hay que abrir el puerto {port}.',
    'heb.percageRefus': 'perforación imposible: {raison}',
    'heb.annuaireEteint': 'directorio apagado — tu servidor solo es visible para quienes les des la dirección.',
    'heb.expulse': '{nom} fue expulsado.',
    'heb.banni': '{nom} fue baneado.',
    'heb.donneCible': 'Escribe el apodo de la persona.',

    'err.serveurIntrouvable': 'El servidor incluido no se encuentra en el lanzador.',
    'err.serveurPasDemarre': 'El servidor no arrancó. Mira el registro de abajo.',
    'err.aucuneSauvegarde': 'No hay partida que compartir: abre el juego y crea una primero.',
    'err.donnees': 'Carpeta de datos no encontrada.',
    'err.sauvegardes': 'Carpeta de partidas no encontrada. Abre el juego una vez y vuelve a intentarlo.',
    'chat.global': 'Todos',
    'chat.local': 'A mi alrededor',
    'chat.equipe': 'Mi equipo',

    'cmd.placeholder': 'Un comando del servidor, por ejemplo /joueurs',
    'cmd.envoyer': 'Enviar',
    'cmd.aide': 'Escribe /aide para la lista. El servidor decide qué te está permitido.',

    'partie.titre': 'La partida',
    'partie.joueurs': 'Quién está aquí',
    'partie.vide': 'Conéctate a un servidor para ver la partida.',
    'partie.equipes': 'Equipos',
    'partie.aucuneEquipe': 'Sin equipos. En el juego: /equipe creer Faro',
    'partie.activites': 'Objetivos',
    'partie.aucuneActivite': 'Sin objetivos. En el juego: /activite creer Reparar el generador | Encontrar la pieza',
    'partie.mesures': '{joueurs} jugador(es) · {entrant} kB/s entrantes · tick {tick} ms · {memoire} MB',
    'partie.mesuresInconnues': 'Métricas no disponibles en este servidor.',
    'partie.pret': 'listo',

    'coffre.titre': 'Arcón común',
    'coffre.contenu': 'Lo que contiene',
    'coffre.vide': 'Vacío por ahora. En el juego, F10 lo muestra.',
    'coffre.objet': 'Nombre del objeto, tal como lo llama el juego',
    'coffre.deposer': 'Depositar',
    'coffre.retirer': 'Retirar',
    'coffre.aide':
      'El servidor guarda el arcón y retira el objeto antes de anunciarlo, así nada se duplica. Es la única forma de pasar objetos entre dos partidas distintas.',
    'coffre.envoye': 'Solicitud enviada al servidor.',

    'ident.titre': 'Tu identidad',
    'ident.detail':
      'Una clave creada en esta máquina. Esta huella es la que un anfitrión anota para darte un rol. La parte privada nunca sale de aquí.',
    'ident.copier': 'Copiar',
    'ident.copie': 'Huella copiada.',
    'ident.refaireTitre': 'Empezar de cero',
    'ident.refaireDetail':
      'Una identidad nueva te vuelve desconocido en todas partes: roles, perfil y horas de juego quedan con la anterior. La clave antigua se aparta, no se borra.',
    'ident.refaire': 'Nueva identidad',
    'ident.confirme': 'Volverás a ser desconocido en todos los servidores. ¿Continuar?',
    'ident.refait': 'Nueva identidad: {empreinte}',

    'nav.installation': 'Instalación',
    'nav.serveurs': 'Servidores',
    'nav.diagnostic': 'Diagnóstico',
    'nav.reglages': 'Ajustes',

    'inst.titreJeu': 'El juego',
    'inst.jeu': 'The Last Caretaker',
    'inst.recherche': 'Buscándolo…',
    'inst.introuvable': 'No encontrado. Pulsa «Elegir» e indica la carpeta del juego.',
    'inst.choisir': 'Elegir',
    'inst.aInstaller': 'Lo que hay que instalar',
    'inst.ue4ssDetail': 'La base que hace funcionar los mods. El lanzador lo incluye, no hay que descargar nada.',
    'inst.telecharger': 'Instalar UE4SS',
    'inst.parcourir': 'Ya la tengo',
    'inst.mods': 'Mods Voyage',
    'inst.modsDetail': 'VoyageLien envía tu posición al servidor. VoyageSonde recoge el diagnóstico.',
    'inst.tout': 'Instalar todo',
    'inst.toutDetail':
      'Un clic: descarga UE4SS, lo instala en el juego junto a nuestros mods y comprueba el resultado.',
    'inst.toutBouton': 'Instalar todo',
    'inst.retirer': 'Quitar',
    'inst.reversible': 'Un UE4SS ya instalado no se toca, ni tus otros mods. Reversible.',
    'inst.trouve': 'encontrado',
    'inst.absent': 'ausente',
    'inst.installe': 'instalado',
    'inst.aFaire': 'por instalar',
    'inst.dossierEnregistre': 'Carpeta del juego guardada.',
    'inst.ue4ssEnregistre': 'Carpeta UE4SS guardada.',
    'inst.termine': 'Instalación terminada.',
    'inst.retire': 'Quitado del juego.',
    'inst.indiqueJeu': 'Indica primero dónde está el juego.',

    'serv.pseudo': 'Tu nombre',
    'serv.pseudoPlaceholder': 'Tu nombre en la partida',
    'serv.enregistrer': 'Guardar',
    'serv.pseudoOk': 'Te llamarás «{nom}» en la partida.',
    'serv.ajouter': 'Añadir un servidor',
    'serv.adressePlaceholder': 'dirección:puerto',
    'serv.boutonAjouter': 'Añadir',
    'serv.actualiser': 'Actualizar',
    'serv.ajoute': 'Servidor añadido.',
    'serv.tiens': 'Tus servidores',
    'serv.aucun': 'Ningún servidor guardado. Añade su dirección arriba.',
    'serv.interrogation': 'Consultando…',
    'serv.enLigne': 'en línea',
    'serv.horsLigne': 'fuera de línea',
    'serv.muet': 'no responde',
    'serv.joueurs': 'jugadores',
    'serv.protege': 'contraseña',
    'serv.connecter': 'Conectar',
    'serv.lancer': 'Iniciar el juego',
    'serv.retirer': 'Quitar',
    'serv.motDePasse': 'Contraseña de «{nom}»:',

    'lien.titre': 'El enlace',
    'lien.pas': 'Sin conectar',
    'lien.vers': 'Conectado a {adresse}',
    'lien.deconnecter': 'Desconectar',
    'chat.titre': 'Hablar con los demás',
    'chat.sousTitre': 'El chat se escribe aquí',
    'chat.aide': 'El juego no puede capturar texto: escribe tu mensaje aquí y aparecerá en la pantalla de todos.',
    'chat.placeholder': 'Tu mensaje…',
    'chat.envoyer': 'Enviar',
    'lien.avant':
      'Conecta primero, luego inicia el juego y carga una partida: tu posición sale sola.',
    'lien.pendant':
      'Inicia el juego y carga una partida: tu posición sale sola. Desde el menú no se envía nada.',
    'lien.demarre': 'Puente iniciado. Inicia el juego y carga una partida.',
    'lien.arrete': 'Puente detenido.',
    'lien.jeuDemarre': 'El juego se está iniciando.',

    'diag.titre': '¿Se carga UE4SS?',
    'diag.analyser': 'Analizar',
    'diag.analyserTitre': 'Analizar la instalación',
    'diag.analyserDetail': 'Ejecuta el juego al menos una vez y vuelve a analizar.',
    'diag.cliqueAnalyser': 'Pulsa «Analizar».',
    'diag.accroche': 'Punto de enganche',
    'diag.accrocheDetail':
      'Un juego solo carga las DLL que importa. Si UE4SS sigue mudo, prueba con otro.',
    'diag.changer': 'Cambiar',
    'diag.enPlace': 'Puesto: {liste}',
    'diag.aucuneAccroche': 'Ningún punto de enganche instalado.',
    'diag.charge': 'UE4SS se carga',
    'diag.chargeOui': 'UE4SS.log escrito el {date}',
    'diag.chargeNon': 'No hay UE4SS.log. El juego no carga la DLL: cambia el enganche abajo.',
    'diag.modVu': 'UE4SS ve nuestros mods',
    'diag.modVuOui': 'Aparecen en el registro.',
    'diag.modVuNon': 'No aparecen en el registro de UE4SS.',
    'diag.rapport': 'Informe de la sonda',
    'diag.rapportOui': 'VoyageSonde.txt encontrado.',
    'diag.rapportNon': 'Aún no escrito: inicia el juego y deja que llegue al menú.',
    'diag.oui': 'sí',
    'diag.non': 'no',
    'diag.accrocheChangee': 'Enganche: {nom}. Reinicia el juego y analiza de nuevo.',
    'diag.console': 'La consola del juego no está en F8: es la tecla a la izquierda del 1, ² / ~, o F10.',

    'regl.langue': 'Idioma',
    'regl.langueDetail': 'Se aplica de inmediato y se recuerda.',
    'regl.aPropos': 'Acerca de',
    'regl.version': 'Versión {v}',
    'regl.aProposDetail':
      'Lanzador independiente para el cooperativo de The Last Caretaker. No incluye ningún archivo del juego y no toca nada fuera de su carpeta.',
    'regl.dossiers': 'Carpetas',
    'regl.ouvrirJeu': 'Abrir la carpeta del juego',

    'tele.enCours': 'Descargando UE4SS… {pourcent} %',
    'tele.extraction': 'Extrayendo…',
    'tele.fini': 'UE4SS {version} instalado.',
    'jrn.jeuTrouve': 'Juego encontrado: {dossier}',
    'jrn.ue4ssTelecharge': 'UE4SS {version} descargado.',
    'jrn.ue4ssDeja': 'UE4SS ya está aquí: solo se añaden nuestros mods.',
    'jrn.egare': 'Quitado de una carpeta inútil: {chemin}',
    'jrn.ue4ssInstalle': 'UE4SS instalado.',
    'jrn.ue4ssGarde': 'UE4SS se deja tal cual: no lo instalamos nosotros.',
    'err.archiveAbsente': 'No se encuentra el archivo de UE4SS incluido en el lanzador.',
    'err.archiveAlteree': 'El archivo de UE4SS incluido no coincide con su huella.',
    'err.extraction': 'No se pudo extraer el archivo de UE4SS.',
    'err.ue4ssManquant': 'Falta UE4SS y no se indicó ninguna fuente.',
    'jrn.console': 'Consola de UE4SS activada (demuestra que se carga).',
    'jrn.modPose': 'Mod «{nom}» colocado.',
    'jrn.modActive': '«{nom}» activado en mods.txt.',
    'jrn.retire': '{quoi} quitado.',

    'lien.demarrage': 'iniciando el puente hacia {adresse}…',
    'lien.pasDemarre': 'el puente no pudo iniciarse: {raison}',
    'lien.fini': 'puente detenido.',
    'lien.finiCode': 'puente detenido (código {code}).',

    'err.binaires': 'No se encuentra Binaries/Win64 en el juego.',
    'err.pasBinaires': 'Esta carpeta no contiene Binaries/Win64. Elige la carpeta del juego.',
    'err.pasUne4ss': 'Esta carpeta no parece una release de UE4SS (se esperan dwmapi.dll y ue4ss/).',
    'err.pasDwmapi': 'dwmapi.dll no está aquí. Elige la carpeta extraída de la release de UE4SS.',
    'err.indiqueUe4ss': 'Indica primero dónde está UE4SS, o pulsa «Descargar».',
    'err.jeuIntrouvable': 'No se encuentra el juego. Indica su carpeta primero.',
    'err.installIncomplete': 'La instalación terminó pero falta algo.',
    'err.accrocheInconnue': 'Punto de enganche desconocido.',
    'err.ue4ssPasInstalle': 'UE4SS no está instalado: instálalo primero.',
    'err.pontIntrouvable': 'Falta el puente en el lanzador.',
    'err.dossierInconnu': 'Carpeta desconocida.',
    'err.dossierDisparu': 'Esa carpeta ya no existe.',
    'err.pseudoVide': 'Elige un nombre.',
    'err.pasDeRapport': 'Todavía no hay informe. Inicia el juego y deja que llegue al menú.',
    'err.archivePasUe4ss': 'El archivo descargado no parece UE4SS.',
    'nav.monde': 'Mundo',
    'monde.tienne': 'Tu partida',
    'monde.dossier': 'Carpeta de partidas guardadas',
    'monde.aucunDossier': 'No encontrada. El juego guarda en tu perfil, no en su propia carpeta.',
    'monde.fichiers': '{n} archivo(s)',
    'monde.publierTitre': 'Publicar tu partida en el servidor',
    'monde.publierDetail': 'Los demás podrán instalarla y jugar en TU mundo. Hace falta la contraseña del mundo.',
    'monde.publier': 'Publicar',
    'monde.mettreDeCote': 'Copiar aparte',
    'monde.nomPlaceholder': 'Nombre del mundo (p. ej. La Balsa)',
    'monde.etiquettePlaceholder': 'Nombre de la partida en el juego',
    'monde.motDePasseMonde': 'Contraseña del mundo (la del anfitrión, no la del servidor):',
    'monde.duServeur': 'El mundo del servidor',
    'monde.aucunDistant': 'Ningún mundo publicado',
    'monde.choisirServeur': 'Elige un servidor y pulsa «Vista previa».',
    'monde.publieLe': '«{nom}» por {par}, {fichiers} archivo(s), {ko} kB — {date}',
    'monde.apercu': 'Vista previa',
    'monde.installer': 'Instalar este mundo',
    'monde.ceQuiChange': 'Lo que cambia la instalación',
    'monde.avertissement': 'Instalar un mundo SUSTITUYE tus partidas del mismo nombre. Antes se hace una copia de la tuya, automáticamente.',
    'monde.resume': '{ajoutes} añadido(s) · {remplaces} sustituido(s) · {locaux} solo tuyo(s)',
    'monde.refusees': '{n} archivo(s) rechazado(s) por seguridad: {liste}',
    'monde.coffre': 'Tus copias de seguridad',
    'monde.aucuneCopie': 'Aún no hay copias. Se hace una en cada instalación.',
    'monde.restaurer': 'Restaurar',
    'monde.publieOk': 'Mundo publicado: «{nom}».',
    'monde.installeOk': '{n} archivo(s) instalado(s). Carga la partida «{etiquette}» en el juego.',
    'monde.restaureOk': '{n} archivo(s) restaurado(s).',
    'monde.copieOk': 'Copia hecha: {chemin}',
    'monde.aucunServeur': 'Añade primero un servidor en la pestaña Servidores.',
    'erreur.inconnue': 'Error desconocido.',
  },
}

const LANGUES_NOMS = { fr: 'Français', en: 'English', es: 'Español' }

let LANGUES_courante = 'fr'

/** Traduit une clé, en remplaçant {ce_genre} de marqueur. */
function T(cle, valeurs) {
  const table = LANGUES_TEXTES[LANGUES_courante] ?? LANGUES_TEXTES.fr
  let texte = table[cle] ?? LANGUES_TEXTES.fr[cle] ?? cle
  if (valeurs) {
    for (const [k, v] of Object.entries(valeurs)) texte = texte.replaceAll(`{${k}}`, String(v))
  }
  return texte
}

/**
 * Repose toutes les étiquettes de la page.
 *
 * ⚠️ textContent, JAMAIS innerHTML : ces textes sont à nous, mais l'habitude
 *    compte — la même fonction servira un jour à un texte venu d'ailleurs.
 */
function LANGUES_appliquer(langue) {
  if (LANGUES_TEXTES[langue]) LANGUES_courante = langue
  document.documentElement.lang = LANGUES_courante

  for (const el of document.querySelectorAll('[data-t]')) el.textContent = T(el.dataset.t)
  for (const el of document.querySelectorAll('[data-t-ph]')) el.placeholder = T(el.dataset.tPh)
  for (const el of document.querySelectorAll('[data-t-titre]')) el.title = T(el.dataset.tTitre)
}
