'use strict'

/**
 * ═══════════════════════════════════════════════════════════════════════════
 *  TROIS LANGUES
 * ═══════════════════════════════════════════════════════════════════════════
 *  ⚠️ CE FICHIER EST UN SCRIPT CLASSIQUE, PAS UN MODULE. Il partage donc sa
 *     portee avec `app.js` : un nom declare deux fois en `const` fait planter
 *     TOUT le script, et l'interface reste figee sans un mot d'erreur
 *     visible. D'ou le prefixe `LANGUES_` sur chaque nom d'ici.
 *
 *  ⚠️ LE FRANCAIS EST LA REFERENCE. Une cle absente d'une traduction retombe
 *     dessus plutot que d'afficher la cle brute a l'utilisateur.
 */

const LANGUES_TEXTES = {
  fr: {
    'appli.titre': 'Lanceur',
    'appli.sousTitre': 'Coopération pour The Last Caretaker — Symbiose Héritage',
    'appli.pied': 'Projet indépendant — aucun fichier du jeu n’est distribué',

    'nav.installation': 'Installation',
    'nav.serveurs': 'Serveurs',
    'nav.diagnostic': 'Diagnostic',
    'nav.reglages': 'Réglages',

    'inst.titreJeu': 'Le jeu',
    'inst.jeu': 'The Last Caretaker',
    'inst.recherche': 'Recherche en cours…',
    'inst.introuvable': 'Introuvable. Clique sur « Choisir » et indique le dossier du jeu.',
    'inst.choisir': 'Choisir',
    'inst.aInstaller': 'Ce qu’il faut installer',
    'inst.ue4ssDetail': 'Le socle qui fait tourner les mods. Le lanceur le livre avec lui, rien à télécharger.',
    'inst.telecharger': 'Installer UE4SS',
    'inst.parcourir': 'J’en ai déjà un',
    'inst.mods': 'Mods Voyage',
    'inst.modsDetail': 'VoyageLien envoie ta position au serveur. VoyageSonde relève de quoi diagnostiquer.',
    'inst.tout': 'Tout installer',
    'inst.toutDetail':
      'Un clic : télécharge UE4SS, l’installe dans le jeu avec nos mods, et vérifie que tout est en place.',
    'inst.toutBouton': 'Tout installer',
    'inst.retirer': 'Retirer',
    'inst.installer': 'Installer',
    'inst.reversible': 'Un UE4SS déjà en place n’est pas touché, et tes autres mods non plus. Réversible.',
    'inst.trouve': 'trouvé',
    'inst.absent': 'absent',
    'inst.installe': 'installé',
    'inst.aFaire': 'à installer',
    'inst.dossierEnregistre': 'Dossier du jeu enregistré.',
    'inst.ue4ssEnregistre': 'Dossier UE4SS enregistré.',
    'inst.termine': 'Installation terminée.',
    'inst.retire': 'Retiré du jeu.',
    'inst.indiqueJeu': 'Indique d’abord où est le jeu.',

    'serv.pseudo': 'Ton pseudo',
    'serv.pseudoPlaceholder': 'Ton nom dans la partie',
    'serv.enregistrer': 'Enregistrer',
    'serv.pseudoOk': 'Tu t’appelleras « {nom} » en partie.',
    'serv.ajouter': 'Ajouter un serveur',
    'serv.adressePlaceholder': 'adresse:port',
    'serv.boutonAjouter': 'Ajouter',
    'serv.actualiser': 'Actualiser',
    'serv.ajoute': 'Serveur ajouté.',
    'serv.tiens': 'Tes serveurs',
    'serv.aucun': 'Aucun serveur enregistré. Ajoute son adresse au-dessus.',
    'serv.interrogation': 'Interrogation…',
    'serv.enLigne': 'en ligne',
    'serv.horsLigne': 'hors ligne',
    'serv.muet': 'ne répond pas',
    'serv.joueurs': 'joueurs',
    'serv.protege': 'mot de passe',
    'serv.connecter': 'Connecter',
    'serv.lancer': 'Lancer le jeu',
    'serv.retirer': 'Retirer',
    'serv.motDePasse': 'Mot de passe de « {nom} » :',

    'lien.titre': 'Le lien',
    'lien.pas': 'Pas connecté',
    'lien.vers': 'Connecté à {adresse}',
    'lien.deconnecter': 'Déconnecter',
    'lien.avant':
      'Connecte-toi d’abord, puis lance le jeu et charge une partie : ta position part toute seule.',
    'lien.pendant':
      'Lance le jeu et charge une partie : ta position part toute seule. Au menu, rien n’est envoyé.',
    'lien.demarre': 'Pont démarré. Lance le jeu et charge une partie.',
    'lien.arrete': 'Pont arrêté.',
    'lien.jeuDemarre': 'Le jeu démarre.',

    'diag.titre': 'Est-ce qu’UE4SS se charge ?',
    'diag.analyser': 'Analyser',
    'diag.analyserTitre': 'Analyser l’installation',
    'diag.analyserDetail': 'Lance le jeu au moins une fois, puis reviens analyser.',
    'diag.cliqueAnalyser': 'Clique sur « Analyser ».',
    'diag.accroche': 'Point d’accroche',
    'diag.accrocheDetail':
      'Un jeu ne charge que les DLL qu’il importe. Si UE4SS reste muet, essaie-en un autre.',
    'diag.changer': 'Changer',
    'diag.enPlace': 'En place : {liste}',
    'diag.aucuneAccroche': 'Aucun point d’accroche installé.',
    'diag.charge': 'UE4SS se charge',
    'diag.chargeOui': 'UE4SS.log écrit le {date}',
    'diag.chargeNon': 'Aucun UE4SS.log. Le jeu ne charge pas la DLL : change de point d’accroche ci-dessous.',
    'diag.modVu': 'Nos mods sont vus par UE4SS',
    'diag.modVuOui': 'Ils apparaissent dans le journal.',
    'diag.modVuNon': 'Ils n’apparaissent pas dans le journal d’UE4SS.',
    'diag.rapport': 'Rapport de la sonde',
    'diag.rapportOui': 'VoyageSonde.txt trouvé.',
    'diag.rapportNon': 'Pas encore écrit : lance le jeu et laisse-le arriver au menu.',
    'diag.oui': 'oui',
    'diag.non': 'non',
    'diag.accrocheChangee': 'Point d’accroche : {nom}. Relance le jeu, puis analyse de nouveau.',
    'diag.console':
      'La console du jeu n’est pas sur F8 : c’est la touche à gauche du 1, ² / ~, ou F10.',

    'regl.langue': 'Langue',
    'regl.langueDetail': 'Elle s’applique tout de suite et sera retenue.',
    'regl.aPropos': 'À propos',
    'regl.version': 'Version {v}',
    'regl.aProposDetail':
      'Lanceur indépendant pour la coopération sur The Last Caretaker. Il n’embarque aucun fichier du jeu et ne modifie rien hors du dossier du jeu.',
    'regl.dossiers': 'Dossiers',
    'regl.ouvrirJeu': 'Ouvrir le dossier du jeu',

    'tele.enCours': 'Téléchargement d’UE4SS… {pourcent} %',
    'tele.extraction': 'Extraction…',
    'tele.fini': 'UE4SS {version} installé.',
    'tele.erreur': 'Le téléchargement a échoué : {raison}',
    'jrn.jeuTrouve': 'Jeu trouvé : {dossier}',
    'jrn.ue4ssTelecharge': 'UE4SS {version} téléchargé.',
    'jrn.ue4ssDeja': 'UE4SS déjà en place : on ajoute seulement nos mods.',
    'jrn.egare': 'Retiré d’un dossier inutile : {chemin}',
    'jrn.ue4ssInstalle': 'UE4SS installé.',
    'jrn.ue4ssGarde': 'UE4SS laissé en place : il n’a pas été installé par nous.',
    'err.archiveAbsente': 'L’archive UE4SS livrée avec le lanceur est introuvable.',
    'err.archiveAlteree': 'L’archive UE4SS livrée ne correspond pas à son empreinte.',
    'err.extraction': 'Impossible d’extraire l’archive UE4SS.',
    'err.ue4ssManquant': 'UE4SS est absent et aucune source n’a été fournie.',
    'jrn.console': 'Console UE4SS activée (elle prouve qu’il se charge).',
    'jrn.modPose': 'Mod « {nom} » posé.',
    'jrn.modActive': '« {nom} » activé dans mods.txt.',
    'jrn.retire': '{quoi} retiré.',

    'lien.demarrage': 'démarrage du pont vers {adresse}…',
    'lien.pasDemarre': 'le pont n’a pas pu démarrer : {raison}',
    'lien.fini': 'pont arrêté.',
    'lien.finiCode': 'pont arrêté (code {code}).',

    'err.binaires': 'Binaries/Win64 est introuvable dans le jeu.',
    'err.pasBinaires': 'Ce dossier ne contient pas Binaries/Win64. Choisis le dossier du jeu lui-même.',
    'err.pasUne4ss': 'Ce dossier ne ressemble pas à une release UE4SS (dwmapi.dll et ue4ss/ attendus).',
    'err.pasDwmapi': 'dwmapi.dll est introuvable ici. Choisis le dossier extrait de la release UE4SS.',
    'err.indiqueUe4ss': 'Indique d’abord où tu as extrait UE4SS, ou clique sur « Télécharger ».',
    'err.jeuIntrouvable': 'Le jeu est introuvable. Indique son dossier d’abord.',
    'err.installIncomplete': 'L’installation s’est terminée mais quelque chose manque.',
    'err.accrocheInconnue': 'Point d’accroche inconnu.',
    'err.ue4ssPasInstalle': 'UE4SS n’est pas installé : installe-le d’abord.',
    'err.pontIntrouvable': 'Le pont est introuvable dans le lanceur.',
    'err.dossierInconnu': 'Dossier inconnu.',
    'err.dossierDisparu': 'Ce dossier n’existe plus.',
    'err.pseudoVide': 'Choisis un pseudo.',
    'err.pasDeRapport': 'Pas encore de rapport. Lance le jeu et laisse-le arriver au menu.',
    'err.archivePasUe4ss': 'L’archive téléchargée ne ressemble pas à UE4SS.',
    'nav.monde': 'Monde',
    'monde.tienne': 'Ta partie',
    'monde.dossier': 'Dossier des sauvegardes',
    'monde.aucunDossier': 'Introuvable. Le jeu range ses parties dans ton profil, pas dans son dossier.',
    'monde.fichiers': '{n} fichier(s)',
    'monde.publierTitre': 'Publier ta partie sur le serveur',
    'monde.publierDetail': 'Les autres pourront l’installer et jouer dans TON monde. Il faut le mot de passe du monde.',
    'monde.publier': 'Publier',
    'monde.mettreDeCote': 'Copier de côté',
    'monde.nomPlaceholder': 'Nom du monde (ex. Le Radeau)',
    'monde.etiquettePlaceholder': 'Nom de la partie dans le jeu',
    'monde.motDePasseMonde': 'Mot de passe du monde (celui de l’hôte, pas celui du serveur) :',
    'monde.duServeur': 'Le monde du serveur',
    'monde.aucunDistant': 'Aucun monde publié',
    'monde.choisirServeur': 'Choisis un serveur, puis « Aperçu ».',
    'monde.publieLe': '« {nom} » par {par}, {fichiers} fichier(s), {ko} ko — {date}',
    'monde.apercu': 'Aperçu',
    'monde.installer': 'Installer ce monde',
    'monde.ceQuiChange': 'Ce que l’installation change',
    'monde.avertissement': 'Installer un monde REMPLACE tes parties du même nom. Une copie de ta partie est faite avant, automatiquement.',
    'monde.resume': '{ajoutes} ajouté(s) · {remplaces} remplacé(s) · {locaux} gardé(s) chez toi',
    'monde.refusees': '{n} fichier(s) refusé(s) par sécurité : {liste}',
    'monde.coffre': 'Tes copies de sauvegarde',
    'monde.aucuneCopie': 'Aucune copie pour l’instant. Il s’en fait une à chaque installation.',
    'monde.restaurer': 'Restaurer',
    'monde.publieOk': 'Monde publié : « {nom} ».',
    'monde.installeOk': '{n} fichier(s) installé(s). Charge la partie « {etiquette} » dans le jeu.',
    'monde.restaureOk': '{n} fichier(s) restauré(s).',
    'monde.copieOk': 'Copie faite : {chemin}',
    'monde.aucunServeur': 'Ajoute d’abord un serveur dans l’onglet Serveurs.',
    'erreur.inconnue': 'Erreur inconnue.',
  },

  en: {
    'appli.titre': 'Launcher',
    'appli.sousTitre': 'Co-op for The Last Caretaker — Symbiose Héritage',
    'appli.pied': 'Independent project — no game files are distributed',

    'nav.installation': 'Setup',
    'nav.serveurs': 'Servers',
    'nav.diagnostic': 'Diagnostics',
    'nav.reglages': 'Settings',

    'inst.titreJeu': 'The game',
    'inst.jeu': 'The Last Caretaker',
    'inst.recherche': 'Looking for it…',
    'inst.introuvable': 'Not found. Click “Choose” and point to the game folder.',
    'inst.choisir': 'Choose',
    'inst.aInstaller': 'What needs installing',
    'inst.ue4ssDetail': 'The layer that runs the mods. The launcher ships it, nothing to download.',
    'inst.telecharger': 'Install UE4SS',
    'inst.parcourir': 'I already have it',
    'inst.mods': 'Voyage mods',
    'inst.modsDetail': 'VoyageLien sends your position to the server. VoyageSonde gathers diagnostics.',
    'inst.tout': 'Install everything',
    'inst.toutDetail':
      'One click: downloads UE4SS, installs it into the game along with our mods, and checks the result.',
    'inst.toutBouton': 'Install everything',
    'inst.retirer': 'Remove',
    'inst.installer': 'Install',
    'inst.reversible': 'An existing UE4SS is left alone, and so are your other mods. Reversible.',
    'inst.trouve': 'found',
    'inst.absent': 'missing',
    'inst.installe': 'installed',
    'inst.aFaire': 'to install',
    'inst.dossierEnregistre': 'Game folder saved.',
    'inst.ue4ssEnregistre': 'UE4SS folder saved.',
    'inst.termine': 'Install finished.',
    'inst.retire': 'Removed from the game.',
    'inst.indiqueJeu': 'Point to the game first.',

    'serv.pseudo': 'Your name',
    'serv.pseudoPlaceholder': 'Your name in game',
    'serv.enregistrer': 'Save',
    'serv.pseudoOk': 'You’ll be “{nom}” in game.',
    'serv.ajouter': 'Add a server',
    'serv.adressePlaceholder': 'address:port',
    'serv.boutonAjouter': 'Add',
    'serv.actualiser': 'Refresh',
    'serv.ajoute': 'Server added.',
    'serv.tiens': 'Your servers',
    'serv.aucun': 'No server saved yet. Add its address above.',
    'serv.interrogation': 'Asking…',
    'serv.enLigne': 'online',
    'serv.horsLigne': 'offline',
    'serv.muet': 'no answer',
    'serv.joueurs': 'players',
    'serv.protege': 'password',
    'serv.connecter': 'Connect',
    'serv.lancer': 'Start the game',
    'serv.retirer': 'Remove',
    'serv.motDePasse': 'Password for “{nom}”:',

    'lien.titre': 'The link',
    'lien.pas': 'Not connected',
    'lien.vers': 'Connected to {adresse}',
    'lien.deconnecter': 'Disconnect',
    'lien.avant': 'Connect first, then start the game and load a save: your position goes on its own.',
    'lien.pendant':
      'Start the game and load a save: your position goes on its own. Nothing is sent from the menu.',
    'lien.demarre': 'Bridge started. Start the game and load a save.',
    'lien.arrete': 'Bridge stopped.',
    'lien.jeuDemarre': 'The game is starting.',

    'diag.titre': 'Is UE4SS loading?',
    'diag.analyser': 'Analyse',
    'diag.analyserTitre': 'Analyse the install',
    'diag.analyserDetail': 'Run the game at least once, then come back and analyse.',
    'diag.cliqueAnalyser': 'Click “Analyse”.',
    'diag.accroche': 'Hook',
    'diag.accrocheDetail': 'A game only loads the DLLs it imports. If UE4SS stays silent, try another.',
    'diag.changer': 'Change',
    'diag.enPlace': 'In place: {liste}',
    'diag.aucuneAccroche': 'No hook installed.',
    'diag.charge': 'UE4SS loads',
    'diag.chargeOui': 'UE4SS.log written on {date}',
    'diag.chargeNon': 'No UE4SS.log. The game isn’t loading the DLL: change the hook below.',
    'diag.modVu': 'UE4SS sees our mods',
    'diag.modVuOui': 'They show up in the log.',
    'diag.modVuNon': 'They don’t show up in the UE4SS log.',
    'diag.rapport': 'Probe report',
    'diag.rapportOui': 'VoyageSonde.txt found.',
    'diag.rapportNon': 'Not written yet: start the game and let it reach the menu.',
    'diag.oui': 'yes',
    'diag.non': 'no',
    'diag.accrocheChangee': 'Hook: {nom}. Restart the game, then analyse again.',
    'diag.console': 'The game console is not on F8: it’s the key left of 1, ² / ~, or F10.',

    'regl.langue': 'Language',
    'regl.langueDetail': 'Applied right away and remembered.',
    'regl.aPropos': 'About',
    'regl.version': 'Version {v}',
    'regl.aProposDetail':
      'Independent launcher for co-op on The Last Caretaker. It ships no game files and touches nothing outside the game folder.',
    'regl.dossiers': 'Folders',
    'regl.ouvrirJeu': 'Open the game folder',

    'tele.enCours': 'Downloading UE4SS… {pourcent}%',
    'tele.extraction': 'Extracting…',
    'tele.fini': 'UE4SS {version} installed.',
    'tele.erreur': 'Download failed: {raison}',
    'jrn.jeuTrouve': 'Game found: {dossier}',
    'jrn.ue4ssTelecharge': 'UE4SS {version} downloaded.',
    'jrn.ue4ssDeja': 'UE4SS already here: only our mods were added.',
    'jrn.egare': 'Removed from a useless folder: {chemin}',
    'jrn.ue4ssInstalle': 'UE4SS installed.',
    'jrn.ue4ssGarde': 'UE4SS left in place: we did not install it.',
    'err.archiveAbsente': 'The UE4SS archive shipped with the launcher is missing.',
    'err.archiveAlteree': 'The UE4SS archive shipped with the launcher does not match its checksum.',
    'err.extraction': 'The UE4SS archive could not be extracted.',
    'err.ue4ssManquant': 'UE4SS is missing and no source was provided.',
    'jrn.console': 'UE4SS console enabled (it proves UE4SS loads).',
    'jrn.modPose': 'Mod “{nom}” placed.',
    'jrn.modActive': '“{nom}” enabled in mods.txt.',
    'jrn.retire': '{quoi} removed.',

    'lien.demarrage': 'starting the bridge to {adresse}…',
    'lien.pasDemarre': 'the bridge could not start: {raison}',
    'lien.fini': 'bridge stopped.',
    'lien.finiCode': 'bridge stopped (code {code}).',

    'err.binaires': 'Binaries/Win64 cannot be found in the game.',
    'err.pasBinaires': 'This folder has no Binaries/Win64. Pick the game folder itself.',
    'err.pasUne4ss': 'This folder does not look like a UE4SS release (dwmapi.dll and ue4ss/ expected).',
    'err.pasDwmapi': 'dwmapi.dll is not here. Pick the folder you extracted the UE4SS release into.',
    'err.indiqueUe4ss': 'Point to your UE4SS folder first, or click “Download”.',
    'err.jeuIntrouvable': 'The game cannot be found. Point to its folder first.',
    'err.installIncomplete': 'The install finished but something is missing.',
    'err.accrocheInconnue': 'Unknown hook.',
    'err.ue4ssPasInstalle': 'UE4SS is not installed: install it first.',
    'err.pontIntrouvable': 'The bridge is missing from the launcher.',
    'err.dossierInconnu': 'Unknown folder.',
    'err.dossierDisparu': 'That folder is gone.',
    'err.pseudoVide': 'Pick a name.',
    'err.pasDeRapport': 'No report yet. Start the game and let it reach the menu.',
    'err.archivePasUe4ss': 'The downloaded archive does not look like UE4SS.',
    'nav.monde': 'World',
    'monde.tienne': 'Your save',
    'monde.dossier': 'SaveGames folder',
    'monde.aucunDossier': 'Not found. The game keeps saves in your profile, not in its own folder.',
    'monde.fichiers': '{n} file(s)',
    'monde.publierTitre': 'Publish your save to the server',
    'monde.publierDetail': 'Others can install it and play in YOUR world. The world password is required.',
    'monde.publier': 'Publish',
    'monde.mettreDeCote': 'Copy aside',
    'monde.nomPlaceholder': 'World name (e.g. The Raft)',
    'monde.etiquettePlaceholder': 'Save name inside the game',
    'monde.motDePasseMonde': 'World password (the host’s, not the server’s):',
    'monde.duServeur': 'The server’s world',
    'monde.aucunDistant': 'No world published',
    'monde.choisirServeur': 'Pick a server, then “Preview”.',
    'monde.publieLe': '“{nom}” by {par}, {fichiers} file(s), {ko} kB — {date}',
    'monde.apercu': 'Preview',
    'monde.installer': 'Install this world',
    'monde.ceQuiChange': 'What installing changes',
    'monde.avertissement': 'Installing a world REPLACES your saves of the same name. A copy of your save is made first, automatically.',
    'monde.resume': '{ajoutes} added · {remplaces} replaced · {locaux} kept, yours only',
    'monde.refusees': '{n} file(s) refused for safety: {liste}',
    'monde.coffre': 'Your backups',
    'monde.aucuneCopie': 'No backup yet. One is made on every install.',
    'monde.restaurer': 'Restore',
    'monde.publieOk': 'World published: “{nom}”.',
    'monde.installeOk': '{n} file(s) installed. Load the “{etiquette}” save in game.',
    'monde.restaureOk': '{n} file(s) restored.',
    'monde.copieOk': 'Copy made: {chemin}',
    'monde.aucunServeur': 'Add a server in the Servers tab first.',
    'erreur.inconnue': 'Unknown error.',
  },

  es: {
    'appli.titre': 'Lanzador',
    'appli.sousTitre': 'Cooperativo para The Last Caretaker — Symbiose Héritage',
    'appli.pied': 'Proyecto independiente — no se distribuye ningún archivo del juego',

    'nav.installation': 'Instalación',
    'nav.serveurs': 'Servidores',
    'nav.diagnostic': 'Diagnóstico',
    'nav.reglages': 'Ajustes',

    'inst.titreJeu': 'El juego',
    'inst.jeu': 'The Last Caretaker',
    'inst.recherche': 'Buscándolo…',
    'inst.introuvable': 'No encontrado. Pulsa «Elegir» e indica la carpeta del juego.',
    'inst.choisir': 'Elegir',
    'inst.aInstaller': 'Lo que hay que instalar',
    'inst.ue4ssDetail': 'La base que hace funcionar los mods. El lanzador lo incluye, no hay que descargar nada.',
    'inst.telecharger': 'Instalar UE4SS',
    'inst.parcourir': 'Ya la tengo',
    'inst.mods': 'Mods Voyage',
    'inst.modsDetail': 'VoyageLien envía tu posición al servidor. VoyageSonde recoge el diagnóstico.',
    'inst.tout': 'Instalar todo',
    'inst.toutDetail':
      'Un clic: descarga UE4SS, lo instala en el juego junto a nuestros mods y comprueba el resultado.',
    'inst.toutBouton': 'Instalar todo',
    'inst.retirer': 'Quitar',
    'inst.installer': 'Instalar',
    'inst.reversible': 'Un UE4SS ya instalado no se toca, ni tus otros mods. Reversible.',
    'inst.trouve': 'encontrado',
    'inst.absent': 'ausente',
    'inst.installe': 'instalado',
    'inst.aFaire': 'por instalar',
    'inst.dossierEnregistre': 'Carpeta del juego guardada.',
    'inst.ue4ssEnregistre': 'Carpeta UE4SS guardada.',
    'inst.termine': 'Instalación terminada.',
    'inst.retire': 'Quitado del juego.',
    'inst.indiqueJeu': 'Indica primero dónde está el juego.',

    'serv.pseudo': 'Tu nombre',
    'serv.pseudoPlaceholder': 'Tu nombre en la partida',
    'serv.enregistrer': 'Guardar',
    'serv.pseudoOk': 'Te llamarás «{nom}» en la partida.',
    'serv.ajouter': 'Añadir un servidor',
    'serv.adressePlaceholder': 'dirección:puerto',
    'serv.boutonAjouter': 'Añadir',
    'serv.actualiser': 'Actualizar',
    'serv.ajoute': 'Servidor añadido.',
    'serv.tiens': 'Tus servidores',
    'serv.aucun': 'Ningún servidor guardado. Añade su dirección arriba.',
    'serv.interrogation': 'Consultando…',
    'serv.enLigne': 'en línea',
    'serv.horsLigne': 'fuera de línea',
    'serv.muet': 'no responde',
    'serv.joueurs': 'jugadores',
    'serv.protege': 'contraseña',
    'serv.connecter': 'Conectar',
    'serv.lancer': 'Iniciar el juego',
    'serv.retirer': 'Quitar',
    'serv.motDePasse': 'Contraseña de «{nom}»:',

    'lien.titre': 'El enlace',
    'lien.pas': 'Sin conectar',
    'lien.vers': 'Conectado a {adresse}',
    'lien.deconnecter': 'Desconectar',
    'lien.avant':
      'Conecta primero, luego inicia el juego y carga una partida: tu posición sale sola.',
    'lien.pendant':
      'Inicia el juego y carga una partida: tu posición sale sola. Desde el menú no se envía nada.',
    'lien.demarre': 'Puente iniciado. Inicia el juego y carga una partida.',
    'lien.arrete': 'Puente detenido.',
    'lien.jeuDemarre': 'El juego se está iniciando.',

    'diag.titre': '¿Se carga UE4SS?',
    'diag.analyser': 'Analizar',
    'diag.analyserTitre': 'Analizar la instalación',
    'diag.analyserDetail': 'Ejecuta el juego al menos una vez y vuelve a analizar.',
    'diag.cliqueAnalyser': 'Pulsa «Analizar».',
    'diag.accroche': 'Punto de enganche',
    'diag.accrocheDetail':
      'Un juego solo carga las DLL que importa. Si UE4SS sigue mudo, prueba con otro.',
    'diag.changer': 'Cambiar',
    'diag.enPlace': 'Puesto: {liste}',
    'diag.aucuneAccroche': 'Ningún punto de enganche instalado.',
    'diag.charge': 'UE4SS se carga',
    'diag.chargeOui': 'UE4SS.log escrito el {date}',
    'diag.chargeNon': 'No hay UE4SS.log. El juego no carga la DLL: cambia el enganche abajo.',
    'diag.modVu': 'UE4SS ve nuestros mods',
    'diag.modVuOui': 'Aparecen en el registro.',
    'diag.modVuNon': 'No aparecen en el registro de UE4SS.',
    'diag.rapport': 'Informe de la sonda',
    'diag.rapportOui': 'VoyageSonde.txt encontrado.',
    'diag.rapportNon': 'Aún no escrito: inicia el juego y deja que llegue al menú.',
    'diag.oui': 'sí',
    'diag.non': 'no',
    'diag.accrocheChangee': 'Enganche: {nom}. Reinicia el juego y analiza de nuevo.',
    'diag.console': 'La consola del juego no está en F8: es la tecla a la izquierda del 1, ² / ~, o F10.',

    'regl.langue': 'Idioma',
    'regl.langueDetail': 'Se aplica de inmediato y se recuerda.',
    'regl.aPropos': 'Acerca de',
    'regl.version': 'Versión {v}',
    'regl.aProposDetail':
      'Lanzador independiente para el cooperativo de The Last Caretaker. No incluye ningún archivo del juego y no toca nada fuera de su carpeta.',
    'regl.dossiers': 'Carpetas',
    'regl.ouvrirJeu': 'Abrir la carpeta del juego',

    'tele.enCours': 'Descargando UE4SS… {pourcent} %',
    'tele.extraction': 'Extrayendo…',
    'tele.fini': 'UE4SS {version} instalado.',
    'tele.erreur': 'La descarga falló: {raison}',
    'jrn.jeuTrouve': 'Juego encontrado: {dossier}',
    'jrn.ue4ssTelecharge': 'UE4SS {version} descargado.',
    'jrn.ue4ssDeja': 'UE4SS ya está aquí: solo se añaden nuestros mods.',
    'jrn.egare': 'Quitado de una carpeta inútil: {chemin}',
    'jrn.ue4ssInstalle': 'UE4SS instalado.',
    'jrn.ue4ssGarde': 'UE4SS se deja tal cual: no lo instalamos nosotros.',
    'err.archiveAbsente': 'No se encuentra el archivo de UE4SS incluido en el lanzador.',
    'err.archiveAlteree': 'El archivo de UE4SS incluido no coincide con su huella.',
    'err.extraction': 'No se pudo extraer el archivo de UE4SS.',
    'err.ue4ssManquant': 'Falta UE4SS y no se indicó ninguna fuente.',
    'jrn.console': 'Consola de UE4SS activada (demuestra que se carga).',
    'jrn.modPose': 'Mod «{nom}» colocado.',
    'jrn.modActive': '«{nom}» activado en mods.txt.',
    'jrn.retire': '{quoi} quitado.',

    'lien.demarrage': 'iniciando el puente hacia {adresse}…',
    'lien.pasDemarre': 'el puente no pudo iniciarse: {raison}',
    'lien.fini': 'puente detenido.',
    'lien.finiCode': 'puente detenido (código {code}).',

    'err.binaires': 'No se encuentra Binaries/Win64 en el juego.',
    'err.pasBinaires': 'Esta carpeta no contiene Binaries/Win64. Elige la carpeta del juego.',
    'err.pasUne4ss': 'Esta carpeta no parece una release de UE4SS (se esperan dwmapi.dll y ue4ss/).',
    'err.pasDwmapi': 'dwmapi.dll no está aquí. Elige la carpeta extraída de la release de UE4SS.',
    'err.indiqueUe4ss': 'Indica primero dónde está UE4SS, o pulsa «Descargar».',
    'err.jeuIntrouvable': 'No se encuentra el juego. Indica su carpeta primero.',
    'err.installIncomplete': 'La instalación terminó pero falta algo.',
    'err.accrocheInconnue': 'Punto de enganche desconocido.',
    'err.ue4ssPasInstalle': 'UE4SS no está instalado: instálalo primero.',
    'err.pontIntrouvable': 'Falta el puente en el lanzador.',
    'err.dossierInconnu': 'Carpeta desconocida.',
    'err.dossierDisparu': 'Esa carpeta ya no existe.',
    'err.pseudoVide': 'Elige un nombre.',
    'err.pasDeRapport': 'Todavía no hay informe. Inicia el juego y deja que llegue al menú.',
    'err.archivePasUe4ss': 'El archivo descargado no parece UE4SS.',
    'nav.monde': 'Mundo',
    'monde.tienne': 'Tu partida',
    'monde.dossier': 'Carpeta de partidas guardadas',
    'monde.aucunDossier': 'No encontrada. El juego guarda en tu perfil, no en su propia carpeta.',
    'monde.fichiers': '{n} archivo(s)',
    'monde.publierTitre': 'Publicar tu partida en el servidor',
    'monde.publierDetail': 'Los demás podrán instalarla y jugar en TU mundo. Hace falta la contraseña del mundo.',
    'monde.publier': 'Publicar',
    'monde.mettreDeCote': 'Copiar aparte',
    'monde.nomPlaceholder': 'Nombre del mundo (p. ej. La Balsa)',
    'monde.etiquettePlaceholder': 'Nombre de la partida en el juego',
    'monde.motDePasseMonde': 'Contraseña del mundo (la del anfitrión, no la del servidor):',
    'monde.duServeur': 'El mundo del servidor',
    'monde.aucunDistant': 'Ningún mundo publicado',
    'monde.choisirServeur': 'Elige un servidor y pulsa «Vista previa».',
    'monde.publieLe': '«{nom}» por {par}, {fichiers} archivo(s), {ko} kB — {date}',
    'monde.apercu': 'Vista previa',
    'monde.installer': 'Instalar este mundo',
    'monde.ceQuiChange': 'Lo que cambia la instalación',
    'monde.avertissement': 'Instalar un mundo SUSTITUYE tus partidas del mismo nombre. Antes se hace una copia de la tuya, automáticamente.',
    'monde.resume': '{ajoutes} añadido(s) · {remplaces} sustituido(s) · {locaux} solo tuyo(s)',
    'monde.refusees': '{n} archivo(s) rechazado(s) por seguridad: {liste}',
    'monde.coffre': 'Tus copias de seguridad',
    'monde.aucuneCopie': 'Aún no hay copias. Se hace una en cada instalación.',
    'monde.restaurer': 'Restaurar',
    'monde.publieOk': 'Mundo publicado: «{nom}».',
    'monde.installeOk': '{n} archivo(s) instalado(s). Carga la partida «{etiquette}» en el juego.',
    'monde.restaureOk': '{n} archivo(s) restaurado(s).',
    'monde.copieOk': 'Copia hecha: {chemin}',
    'monde.aucunServeur': 'Añade primero un servidor en la pestaña Servidores.',
    'erreur.inconnue': 'Error desconocido.',
  },
}

const LANGUES_NOMS = { fr: 'Français', en: 'English', es: 'Español' }

let LANGUES_courante = 'fr'

/** Traduit une clé, en remplaçant {ce_genre} de marqueur. */
function T(cle, valeurs) {
  const table = LANGUES_TEXTES[LANGUES_courante] ?? LANGUES_TEXTES.fr
  let texte = table[cle] ?? LANGUES_TEXTES.fr[cle] ?? cle
  if (valeurs) {
    for (const [k, v] of Object.entries(valeurs)) texte = texte.replaceAll(`{${k}}`, String(v))
  }
  return texte
}

/**
 * Repose toutes les étiquettes de la page.
 *
 * ⚠️ textContent, JAMAIS innerHTML : ces textes sont à nous, mais l'habitude
 *    compte — la même fonction servira un jour à un texte venu d'ailleurs.
 */
function LANGUES_appliquer(langue) {
  if (LANGUES_TEXTES[langue]) LANGUES_courante = langue
  document.documentElement.lang = LANGUES_courante

  for (const el of document.querySelectorAll('[data-t]')) el.textContent = T(el.dataset.t)
  for (const el of document.querySelectorAll('[data-t-ph]')) el.placeholder = T(el.dataset.tPh)
  for (const el of document.querySelectorAll('[data-t-titre]')) el.title = T(el.dataset.tTitre)
}
